---
apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-keycloak-credentials
      key: credentials
      namespace: keycloak
