---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuiltinobjects.keycloak.crossplane.io  # required to be in the format <plural>.<group>
spec:
  group: keycloak.crossplane.io
  names:
    kind: XBuiltinObjects
    plural: xbuiltinobjects
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              realm:
                type: string
                description: Realm to import the builtin clients/roles from
              builtinClients:
                type: array
                items:
                  type: string
                description: List of clients to import from the realm 
              builtinRealmRoles:
                type: array
                items:
                  type: string
                  enum:
                    - offline_access
                    - uma_authorization
                    - admin
                    - create-realm
                    - default-roles-master
                description: List of realm roles to import from the realm
              builtinAuthenticationFlows:
                type: array
                items:
                  type: string
                description: List of authentication flows to import from the realm
              providerConfigName:
                type: string
                description: Name of the provider config to attach to the imported clients/roles
              providerSecretName:
                type: string
                description: Name of the secret containing the provider credentials (Secret must have a label with key=type and value=provider-credentials to be found)
            required:
            - providerConfigName
            - providerSecretName
            - realm
        required:
        - spec
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xoidcclients.oidc.homelab.olav.ninja  # required to be in the format <plural>.<group>
spec:
  group: oidc.homelab.olav.ninja
  names:
    kind: XOidcClient
    plural: xoidcclients
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              baseUrl:
                description: Default URL to use when the auth server needs to
                  redirect or link back to the client.
                type: string
              displayName:
                type: string
                description: The display name of this client in the GUI
              clientId:
                type: string
                description: The Client ID for this client, referenced in the URI during authentication and in issued tokens
              clientSecretSecretRef:
                description: |-
                  The client or client secret registered within the identity provider. This field is able to obtain its value from vault, use $${vault.ID} format.
                  Client Secret.
                properties:
                  key:
                    description: The key to select.
                    type: string
                  name:
                    description: Name of the secret.
                    type: string
                  namespace:
                    description: Namespace of the secret.
                    type: string
                required:
                - key
                - name
                - namespace
                type: object
              description:
                type: string
                description: The description of this client in the GUI
              defaultScopes:
                type: array
                items:
                  type: string
                description: |-
                  The default scopes to be requested when asking for authorization
              grantTypes:
                type: array
                items:
                  type: string
                description: |-
                  A list of grant types that should be enabled for the client
              postLogoutRedirectUris:
                type: array
                items:
                  type: string
                description: A list of valid URIs a browser is permitted to redirect
                  to after a successful logout.
              realm:
                type: string
                description: The realm this client is attached to
              redirectUris:
                type: array
                items:
                  type: string
                description: |-
                  A list of valid URIs a browser is permitted to redirect to after a successful login or logout. Simple
                  wildcards in the form of an asterisk can be used here. This attribute must be set if either standard_flow_enabled or implicit_flow_enabled
                  is set to true.
              serviceAccountRoles:
                type: array
                items:
                  type: object
                  properties:
                    client: 
                      type: string 
                    realm:
                      type: string
                    role:
                      type: string
                description: |-
                  A list of roles to assign to the clients service account
              type:
                type: string
                description: Specifies the type of client
              webOrigins:
                type: array
                items:
                  type: string
                description: |-
                  A list of allowed CORS origins. To permit all valid
                  redirect URIs, add +. Note that this will not include the *
                  wildcard. To permit all origins, explicitly add *.
            required:
            - clientId
            - realm
        required:
        - spec
