apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: aria2
  namespace: aria2
spec:
  baseUrl: https://aria2.homelab.olav.ninja
  clientId: aria2
  clientSecretSecretRef:
    key: clientSecret
    name: aria2-oidc-credentials
    namespace: aria2
  description: Aria2 Download Manager
  displayName: Aria2
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://aria2.homelab.olav.ninja/oauth2/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: fileflows
  namespace: fileflows
spec:
  baseUrl: https://fileflows.homelab.olav.ninja
  clientId: fileflows
  clientSecretSecretRef:
    key: clientSecret
    name: fileflows-oidc-credentials
    namespace: fileflows
  description: FileFlows Proxy Client
  displayName: FileFlows
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://fileflows.homelab.olav.ninja/oidc/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: gitea
  namespace: gitea
spec:
  baseUrl: https://gitea.homelab.olav.ninja
  clientId: gitea
  clientSecretSecretRef:
    key: secret
    name: gitea-oidc-credentials
    namespace: gitea
  description: Gitea Client
  displayName: Gitea
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://gitea.homelab.olav.ninja/user/oauth2/keycloak/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: immich
  namespace: immich
spec:
  baseUrl: https://immich.homelab.olav.ninja
  clientId: immich
  clientSecretSecretRef:
    key: clientSecret
    name: immich-oidc-credentials
    namespace: immich
  description: Immich Client
  displayName: Immich
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - app.immich:/
    - https://immich.homelab.olav.ninja/auth/login
    - https://immich.homelab.olav.ninja/user-settings
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  baseUrl: https://jellyfin.homelab.olav.ninja
  clientId: jellyfin
  clientSecretSecretRef:
    key: clientSecret
    name: jellyfin-oidc-credentials
    namespace: jellyfin
  description: Jellyfin Media Server
  displayName: Jellyfin
  grantTypes:
    - code
  postLogoutRedirectUris:
    - https://jellyfin.homelab.olav.ninja/*
  realm: homelab
  redirectUris:
    - https://jellyfin.homelab.olav.ninja/sso/OID/redirect/Keycloak
    - https://jellyfin.homelab.olav.ninja/sso/OID/r/Keycloak
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: netbird
  namespace: netbird
spec:
  baseUrl: https://netbird.homelab.olav.ninja
  clientId: netbird
  defaultScopes:
    - acr
    - basic
    - email
    - profile
    - roles
    - web-origins
    - netbird-api
  description: Netbird Client
  displayName: Netbird
  grantTypes:
    - code
    - device_code
    - password
  groupsClaim: groups
  postLogoutRedirectUris:
    - https://netbird.homelab.olav.ninja/*
  realm: homelab
  redirectUris:
    - http://localhost:53000
    - https://netbird.homelab.olav.ninja/*
  type: PUBLIC
  webOrigins:
    - +
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  baseUrl: https://nextcloud.homelab.olav.ninja
  clientId: nextcloud
  clientSecretSecretRef:
    key: clientSecret
    name: nextcloud-oidc-credentials
    namespace: nextcloud
  description: Nextcloud Client
  displayName: Nextcloud
  grantTypes:
    - code
  postLogoutRedirectUris:
    - https://nextcloud.homelab.olav.ninja/
  realm: homelab
  redirectUris:
    - https://nextcloud.homelab.olav.ninja/apps/user_oidc/code
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: openwebui
  namespace: openwebui
spec:
  baseUrl: https://openwebui.homelab.olav.ninja
  clientId: openwebui
  clientSecretSecretRef:
    key: clientSecret
    name: openwebui-oidc-credentials
    namespace: openwebui
  description: Open WebUI Client
  displayName: Open WebUI
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://openwebui.homelab.olav.ninja/oauth/oidc/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: pingvinshare
  namespace: pingvinshare
spec:
  baseUrl: https://pingvin.homelab.olav.ninja
  clientId: pingvinshare
  clientSecretSecretRef:
    key: clientSecret
    name: pingvinshare-oidc-credentials
    namespace: pingvinshare
  description: Pingvin Share Client
  displayName: Pingvin Share
  grantTypes:
    - code
  postLogoutRedirectUris:
    - https://pingvin.homelab.olav.ninja/*
  realm: homelab
  redirectUris:
    - https://pingvin.homelab.olav.ninja/api/oauth/callback/oidc
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: traefik
  namespace: traefik
spec:
  baseUrl: https://traefik.homelab.olav.ninja
  clientId: traefik
  clientSecretSecretRef:
    key: clientSecret
    name: traefik-oidc-credentials
    namespace: traefik
  description: Traefik Proxy Client
  displayName: traefik
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://traefik.homelab.olav.ninja/oidc/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: kubectl
spec:
  clientId: kubectl
  description: Kubectl Client
  displayName: Kubectl
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - http://localhost:8000
    - http://localhost:18000
  type: PUBLIC
