apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: gitea
  namespace: gitea
spec:
  baseUrl: https://gitea.homelab.olav.ninja
  clientId: gitea
  clientSecretSecretRef:
    key: secret
    name: gitea-oidc-credentials
    namespace: gitea
  description: Gitea Client
  displayName: Gitea
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://gitea.homelab.olav.ninja/user/oauth2/keycloak/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: immich
  namespace: immich
spec:
  baseUrl: https://immich.homelab.olav.ninja
  clientId: immich
  clientSecretSecretRef:
    key: clientSecret
    name: immich-oidc-credentials
    namespace: immich
  description: Immich Client
  displayName: Immich
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - app.immich:/
    - https://immich.homelab.olav.ninja/auth/login
    - https://immich.homelab.olav.ninja/user-settings
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: netbird
  namespace: netbird
spec:
  baseUrl: https://netbird.homelab.olav.ninja
  clientId: netbird
  defaultScopes:
    - acr
    - basic
    - email
    - profile
    - roles
    - web-origins
    - netbird-api
  description: Netbird Client
  displayName: Netbird
  grantTypes:
    - code
    - device_code
    - password
  postLogoutRedirectUris:
    - https://netbird.homelab.olav.ninja/*
  realm: homelab
  redirectUris:
    - http://localhost:53000
    - https://netbird.homelab.olav.ninja/*
  type: PUBLIC
  webOrigins:
    - +
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: netbird-backend
  namespace: netbird
spec:
  clientId: netbird-backend
  clientSecretSecretRef:
    key: clientSecret
    name: netbird-backend-oidc-credentials
    namespace: netbird
  description: Netbird Backend Client
  displayName: Netbird Backend
  grantTypes:
    - client_credentials
    - code
    - device_code
    - password
  realm: homelab
  redirectUris:
    - /*
  serviceAccountRoles:
    - client: builtin-homelab-realm-management
      realm: homelab
      role: view-users
  type: CONFIDENTIAL
  webOrigins:
    - +
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  baseUrl: https://nextcloud.homelab.olav.ninja
  clientId: nextcloud
  clientSecretSecretRef:
    key: clientSecret
    name: nextcloud-oidc-credentials
    namespace: nextcloud
  description: Nextcloud Client
  displayName: Nextcloud
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://nextcloud.homelab.olav.ninja/*
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: openwebui
  namespace: openwebui
spec:
  baseUrl: https://openwebui.homelab.olav.ninja
  clientId: openwebui
  clientSecretSecretRef:
    key: clientSecret
    name: openwebui-oidc-credentials
    namespace: openwebui
  description: Open WebUI Client
  displayName: Open WebUI
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - https://openwebui.homelab.olav.ninja/oauth/oidc/callback
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: pingvinshare
  namespace: pingvinshare
spec:
  baseUrl: https://pingvin.homelab.olav.ninja
  clientId: pingvinshare
  clientSecretSecretRef:
    key: clientSecret
    name: pingvinshare-oidc-credentials
    namespace: pingvinshare
  description: Pingvin Share Client
  displayName: Pingvin Share
  grantTypes:
    - code
  postLogoutRedirectUris:
    - https://pingvin.homelab.olav.ninja/*
  realm: homelab
  redirectUris:
    - https://pingvin.homelab.olav.ninja/api/oauth/callback/oidc
  type: CONFIDENTIAL
---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: kubectl
spec:
  clientId: kubectl
  description: Kubectl Client
  displayName: Kubectl
  grantTypes:
    - code
  realm: homelab
  redirectUris:
    - http://localhost:8000
    - http://localhost:18000
  type: PUBLIC
