apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openwebui

resources:
  - namespace.yaml

helmCharts:
  - name: open-webui
    releaseName: openwebui
    namespace: openwebui
    repo: https://helm.openwebui.com/
    version: 5.4.0
    valuesFile: values.yaml
