apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openwebui

resources:
  - namespace.yaml
  - oidc-client.yaml
  - pvcs.yaml
  - secrets.yaml

helmCharts:
  - name: open-webui
    releaseName: openwebui
    namespace: openwebui
    repo: https://helm.openwebui.com/
    version: 5.11.0
    valuesFile: values.yaml
