ollama:
  enabled: false # Deployed separately

ollamaUrls:
  - https://ollama.homelab.olav.ninja

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      hajimari.io/enable: 'true'
      hajimari.io/icon: https://avatars.githubusercontent.com/u/158137808
  host: openwebui.homelab.olav.ninja
  tls: true
  existingSecret: openwebui-tls-certificate

pipelines:
  enabled: false

persistence:
  enabled: false
