# https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
namespace: cert-manager

config:
  gatewayAPI:
    enabled: true

global:
  leaderElection:
    namespace: cert-manager

installCRDs: true

startupapicheck:
  timeout: 5m
