---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-backend-management
spec:
  template:
    spec:
      initContainers:
      - name: configure
        env:
        - name: NETBIRD_RELAY_URI
          value: "rels://netbird.homelab.olav.ninja:443"
        - name: NETBIRD_RELAY_SECRET
          valueFrom:
            secretKeyRef:
              key: authSecret
              name: netbird-relay-credentials
