---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  annotations:
    crossplane.io/external-name: homelab/realm-management
  name: builtin-homelab-realm-management
spec:
  forProvider:
    realmIdRef: 
      name: homelab
    clientId: realm-management
  providerConfigRef:
    name: default
  managementPolicies: ["Observe"]
