---
apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: builtin-objects-homelab
  namespace: keycloak
spec:
  providerConfigName: default
  providerSecretName: crossplane-keycloak-credentials
  realm: homelab
  builtinAuthenticationFlows:
    - browser
  builtinClients: 
    - account
    - account-console
    - admin-cli
    - broker
    - realm-management
    - security-admin-console
  builtinRealmRoles:
    - offline_access
    - uma_authorization
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-xbuiltinobjects-create
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["keycloak.crossplane.io"]
    resources: ["xbuiltinobjects"]
    verbs: ["get", "list", "create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keycloak-xbuiltinobjects-create
subjects:
- kind: ServiceAccount
  name: keycloak
  namespace: keycloak
roleRef:
  kind: ClusterRole
  name: keycloak-xbuiltinobjects-create
  apiGroup: rbac.authorization.k8s.io
