---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: builtin-homelab-realm-management
spec:
  forProvider:
    realmIdRef: 
      name: homelab
    clientId: realm-management
  providerConfigRef:
    name: default
  managementPolicies: ["Observe"]
