---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
spec:
  encryptedData:
    password: AgBgtRvU9pbVKgL7wZQnogcTXA+I8XO3BqAzialWSeeX3YpYCBbhNELkTe4BcugoYfL+keC/0D2VqiECisYL4arvUkOmHXKBVUsl97rzSKcS8zSomy4OMx3lQWI6xBuB4vwLzDN6qcl+LfnoIJlzcycpgQhdWPPcEJ3utzp/dhO9LzocCW2xHREgaySYSkuaTBdq/Tj2HZKuaJ7hVNgbO00zjHZd7qAs0OVFoZpJlZyMYdZU0S1r0gL+XaP3v2ARZ3XQEDmmxufLOPWcxYOeJ712q8wFZn5sCJdns31sFCFYI5mN/d6iBvcEfuWLnCz1ET0DC6HgedLID1jB3sCjYnQdz92V2fkDyj6uzqb7X9CTKwn6JvY8Egd40KVbamsLuoiT2aNpFw23gkK3Ajus3H5S9aL3k8zCSgBrHBKkO2TZDER6Fzw39cLBSnRBWzPS7wy10JIfRNPKV9rmGlHWY6y+H4KWkPiIlUOqDGjlfaLPXyD9o0DcTs3rTPF/lScqPtqSlKJCEDwWqudC8UKLn5YSPfECdOnqNCDyj586h+FZk0IxU4MSG7HbLHi+B3/Aev3qibBeMIYSsUYGn+B61YY0INm+AEV+M2Co98WU46S7+zIHpxSK6LxV+ov6MIdyo1tGC4PnFd1bIZ2ZxjlUnwMfE8tFSyWO+963ECVcPx0rXbvEDnzKvPsW4f25ttk0zzjX2WLxOfs6fcOKnoeGnG+U
  template:
    metadata:
      name: keycloak-admin-password
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-initial-passwords
  namespace: keycloak
spec:
  encryptedData:
    jiyoung: AgBjfkzNhEWEjBLwuYVxJivGuVUpaDxcKKtLCeudRW1qFDwUeloT/eWE1b8M7n3vAomwXkXO7L6MzZXeloUHhwkT1WSIfxqBVYnjvK/zUD0tYLp6FjXvPjSFMscFU4tvNNc7+teiju9JzMapOo0Omc/Z4yX4PaEVdEUuvKc8oEIyueKq5JE1sU7ZIIg+PohdrzOH2RNUgjloeo1vcH2c/fRWjU9pJlrzx6cpUGZDJL0pUH8ed/k+9ikuRJiNIl5qKzD1EgWn9kmcFlenSaXj/cN462F/JL8DeE+rnU2Tdvg8ijZZnFKWbG7auqqL5Ui4dYaTUcJZkeB+jbRkCB5uwA9e1tomrrdxd9fwAOZHRK51yqRRhEV+Jjh+OlSFYL+mZlHGiLpKcTbv7oKyaLXfZDPy36UPJhJjOQJqBoNRrD8czDTrD3ZEnwzdW9mzt/aKRjBlASX2/XGSe7iFrRx+yJ7wNI3s5kiACxeRZag7v3rFw+/xuf0jG91JRo6LBoiZDZYCbxDAisykRofb9g1N46tKHfYL+2mde/D4HQn4DoLcrvOkFiiRCci9iKZh++jRVnbNwGr204zeHAuXwyHIBCUUKnrZXXhl7eJR87lyTmm53bKug/V11ACUSdrBnnOfoiEBldvg0C6dxNpcUn/sqbm581AKkemGDJKGiwi5SbEnuQ+W4//vMZgx8ML4tCnsCxXYOJsARcPT7z8fpRIOWqw=
    olav: AgAzrh0PKbxUE2vfIdL+iWPb78QmHcvDULvLns8DwMI/I4oLyz5J+DPy8pvEjVNCm3AEyxt3Wj5TanOGNdSCcpP+tp/p1oiWdQGBvq+DAi0S7CfWxKjc+SEne0YUcQLXTMhX7rtdJOVjVf/shjG9Q0eMx8TqX+dnda3PKSD+B+HVpvZaQmnMiVszssp2VUqvw9D9yqlDoK2Nv1d5kQNmX7Mm1+HLdYOkmPnMXMNH9zxQzD/jhkq4i01FgOIQpeu2651GQ2SX8BGPR74sIXijIm4QjETDs1atJNXz6yxG7dSQQ1OMUUhlWUasifAkbo4tLZDpgKXYgQgJA6sR7SkukbEr0JixI3dk93dmBoSUXS9qyf3E0iBKR63jB/Wl2Ba4H2buhrd7rBaF+29zeX0leKWf//hXY0KcpgqKWxwcPVf204/OGBsJ0x6vTZRMd9w0KxiKLV5yng8VKXbrQsnKI3o7ypCRwcVk/AHpBEIUJrOC53R4h307INAdPuM2KOLFDuHukWaM10bbTGJ0NRczCkuq7munS9QzycN6n/U3Yteob6gPTRbMOt9AVd0fWE3sjpbrKOp+78XtTQ58I1JWDhMUHa3rG2XdH2kClbfz+knCzROMB6SyZXp6x0NSfeY6ni86VqkDEnNwEE5qi3GkC+HyYVcjMI1iL+sRZFc+DWGDzMcVLTASzuabPSNGdlLmIEKCCrOczaSLMuGjscZFlPU3
  template:
    metadata:
      name: keycloak-initial-passwords
      namespace: keycloak
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgA+ujL86YIs5ecAexMZ/CgsEBN5VMSYoXV2C0+OKEbmlaNwqBDzlTbFiCMBLe+RIaLTbJ5Lj14HFrGWqx4SdKpIqwJwxtzYJqnUzsQmgHQrAg17OJHgZbMdtI01F13/LrPjaLi0dmygPzO6xw1/bw8RHd1GiAeVorUmQh0Z7zfw33x3YaSb/KC4lCyn+INYOrPG+Gl7WtwKe0g7lLQbkwIl89A37SGHABxErlmuecev6j8CDNQ/WGugHrz/WJK6Z4bNIItMSi0YUeSL60LniEF9Vdx8FrEZ/VMMvyzHz9Sy8X1ygcTKnQi2woKi8QIXi0t1yRAj9HNHmtojh6iDvFtQVldX+OGmCb52iwaS1gybmzPXEs+++vRG1btosXh2t2PGs0SeCvZul+ZVufOfB/i9pRuu6AvVOAqxGz2Z1bRinZfkbrYlweUv5GwZKFTb+xRBx5Umwv1jJ/zngCEEZ+xdAk5iC6IVhqfclW8qcESagEPgIK0ZPwD7KD2iLi9dy3Ob0nd8+jvlnIr1BmwoPc5pf+mbt50OpGAdMlBGfPaYRFFM95pFs3UEX/E0gM/RRWDzgz8c60fyvnV9ACeRLnDqQhMUp3G8z7P6ZndnvVRw9R1n0mXR7yUabUtju63/tHQpY9muJ0m7occD93W+18mUVDPoiBC/sQzppYtqBNo/CJ96L2D0wky/raUNKQQVaiYw/izlXIquW6kn
    postgres-password: AgChWk610AN5uWVgF6/DlIZZ/GJSFfUZi8s0VPluyo6/iT8yKahc1wWW2hnQ2CIfHAlziq/ksLWElPAgpFYSaQAcOLi/uOEi8K4tR994MAMYMX8zh46ZOm4e7da8E8kS7A96aez2cs5J19VPoGbEwteCqB+sZFby+4qLeRPTL6Fk0q8WppnhZDstYwvMYL2gpTeIDqQlwyg360QTHoFa7BAntdpJcO3eA11tTubhV16ImwV348LYo4x1o5fesgazepAope2KhujKuPjBjqEDfMObJUvTTQuXQswmVLG7N4eeBilo/CEAWt7JS4wDODQM1RxLjiySDqJJBjwKxISORX19Np1iPINmTuJddCiS+i4xo6qp25SbExx9AT94TW6bSZrAruJsPPrm30tc90/nGBRnM/kD0CtfOayudmrkli3NMm4fAJ+qWaNTaU4WAiy0jimO5BrPzK+OlCVR7VRh2r6nr83X4BHAYjY7cAiCNF9ptl4G3EKvYnMawM5I3pGCbyr+0XbihEXurphFso5ElvmhzDonv/rzLF+ta/frpYdN2o2I7UUamh+is6u3iYFl/Zh+k8eZuJxZkdY/h2pha5ZL9tjzniGFQxYbWqMZN5suZDBo/YtItHlhx8Jr1o3m7lwpW299P11DFoo8rPHPUfOxTet9iqCDHTTBGx8ymLqG1fnT91WbJP+JIFHY8O9+HnrY2+Wg5aGpDkg9
    username: AgAPDXqoidAyFnMjYy6AHu9w/IS/IyQF7EjGtb3kFaq86nTLvtdSPBgS2V1cEi/Ko8MI8e0B0TA6LfXfvFm85yTDzazGVCRWVDLWBdrt5FEKqg/gUbBZXvC/AcBCxMZxE+cXXLuICz5ogW0Z+nDhgo343IUTG9QgWKXVPVpp2IPqI7ka0IhwbBo9/Q7kd2UwkMDxzNIqgArr/l25fZ59YsjvASI9qFh6rsnSu4idsLGRFJwo5oKJMUVM1K4BaFz5fllBKijTvueLP1FyOMzYjA3DUdu4fr6dmqbZTZu8pzDr4AJdNsYTN54vaZj6+46DHPH29iSYHYHRMGvk4KcJsIOibTxlIxiXS+WzwuaVfPkdAYFwR0vcuBplsFG0yxhNA//bQCtMQIteF3ofGgLtSXdibaXstkuHCCvWR6Mg4/zN/xuDt5qrQW/cPepjKgxqWSObF95BKKp0Tv9fID1K4MlRLI4g+k6j/nMr8hli7ZMtoaQLUa26nnQU9V7dwK/r6GdgCPVtO1gHm5XPL8z4HB5pa7/pxQdieCHLBV9+TFSaEqxhDReje2ZyeLFehQEYdBqEarxqe8L/CNZIQPPzkDNn6X2qmpPiQFiraBOkYB1Q2yr0j5nj6Xuv1ObGlMCvo4fDVW4aWcOquu4IDL2J7nZkON6qbDnMHVoq7/cif8Pf448lA5iqzTRMIGeUlq31EigqJ2g7LNNGGHmUCQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossplane-keycloak-credentials
  namespace: keycloak
spec:
  encryptedData:
    credentials: AgBTjhI8iY1NIToAtBAbRe9qVikwtCVKzH52DYazQICVjjHOBOmG+XHQ0XSnopit6le+ayC9ls2pp3zRMXacMyd6a9x5qmFcO9N0hTxPa9F9O2tuwAjUBaWWegM+WgMu2DXa/9nYdKi0Kz1HSDy0gnB9Wtlmd4Xjbr/tYpDRVTRKizCgs1LLNr7/o6G/ZV0zrJH0Hxt85cZNPjSIoODu4v69ea/Xq8ioqSC6GvfThFQdwx1CZi/TS1OAHarpSWl+i3RfPEls46iLNhHi3t8tD1YumSCENqpFtQ3B1jMc5kAE4kGtsvA9RdrGp8oDLIurmWOzL7HeYSJILrB6cVo7L+Y9wnI+ovCeyqbHeGIjBnYUUYTW7kvubbhBzzdhwDDVsUk5/3TYV8eQoccvYWPfmOhzIGEmBH7jOdD7TfCvbx1TMv2cuMjTGoE2A0WBE+hHY/OgtlWN+Mgvld83KvMLW8cNp2Q4ZhY+syo5okgkAUUqUbsw17bGpBnGObsipdB2j/PqqGTHlNcqskK46TVsu8MPV2MwWcZ/UfDbiEyA9GVYFB8aZXtoNwhXsRLNVS874K3HbtiMoNNWYaZ3ddairQl8uomhEm/H/33IiRJwElFgKfQvQOr5ak6yoBC75NoFetz4fZLr0XgWgB2RvIckb3+WxjrCmc5IdrlrL221otu70T1bZcvZN1vaDA9V2AseY7/WZJuGDqHpfeARkdXzDJd99LPW1Ww6eGBru1BQQWi0obilE+dVEueJ9neebkmZX07OTU1dOQRVvHFQb7k0U39s646mseV5g62d5J+2dnxE9bwoYdy9XY2Hu/oCqPW3ezgyENy0rjwhJo3ua36P2BSkDGI694N7EEb2GjuZSZKlDCWaAmfEGhj4Fw9z
  template:
    metadata:
      labels:
        type: provider-credentials
      name: crossplane-keycloak-credentials
      namespace: keycloak
    type: Opaque
