apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

resources:
  - namespace.yaml

helmCharts:
- name: sealed-secrets
  releaseName: sealed-secrets
  namespace: sealed-secrets
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 2.5.5
  includeCRDs: true
  valuesFile: values.yaml
