apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - namespace.yaml
  - middleware.yaml
  - proxy-external-cluster.yaml

helmCharts:
- name: traefik
  releaseName: traefik
  namespace: traefik
  repo: https://traefik.github.io/charts
  version: 34.4.1
  includeCRDs: true
  valuesFile: values.yaml
