apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - namespace.yaml
  - issuer.yaml
  - secrets.yaml

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  version: v1.16.2
  includeCRDs: true
  valuesFile: values.yaml

patches:
  - path: patches/add-job-ttl.yaml
