auth:
  authority: https://keycloak.homelab.olav.ninja/realms/homelab
  audience: netbird
  device:
    provider: hosted
    audience: netbird
    authority: https://keycloak.homelab.olav.ninja/realms/homelab
    clientID: netbird
    deviceAuthorizationEndpoint: https://keycloak.homelab.olav.ninja/realms/homelab/protocol/openid-connect/auth
    tokenEndpoint: https://keycloak.homelab.olav.ninja/realms/homelab/protocol/openid-connect/token
    scope: openid
    useIDToken: false

idp:
  managerType: keycloak
  clientID: netbird-backend
  secretKeyRef:
    name: netbird-backend-oidc-credentials
    key: clientSecret
  grantType: client_credentials
  adminEndpoint: https://keycloak.homelab.olav.ninja/admin/realms/homelab
  tokenEndpoint: https://keycloak.homelab.olav.ninja/realms/homelab/protocol/openid-connect/token

management:
  image:
    tag: 0.43.2 # renovate: docker=netbirdio/management
  dnsDomain: netbird
  persistentVolume:
    enabled: true
    size: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /api
            pathType: Prefix
          - path: /management.ManagementService/
            pathType: Prefix
    tls:
      - secretName: netbird-tls-certificate
        hosts:
          - netbird.homelab.olav.ninja

signal:
  image:
    tag: 0.43.2 # renovate: docker=netbirdio/signal
  uri: netbird.homelab.olav.ninja:443
  protocol: https
  persistentVolume:
    enabled: true
    size: 1Gi
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /signalexchange.SignalExchange/
            pathType: Prefix
    tls:
      - secretName: netbird-tls-certificate
        hosts:
          - netbird.homelab.olav.ninja

stun:
  uri: stun:coturn.homelab.olav.ninja:3478

turn:
  uri: turn:coturn.homelab.olav.ninja:3478
  user: netbird
  secretKeyRef:
    name: netbird-turn-credentials
    key: password