apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./cert-manager
  - ./cilium
  - ./cloudnative-pg
  - ./coturn
  - ./crossplane
  - ./device-plugins
  - ./hajimari
  - ./keycloak
  - ./longhorn
  - ./netbird
  - ./oidc-config
  - ./proxmox-ccm
  - ./proxmox-csi
  - ./sealed-secrets
  - ./traefik
