apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-proxy-token
  namespace: netbird
spec:
  encryptedData:
    token: AgAD8sDQEMzv1GJeTm/EzDYRC1Evu3vaimS/lIDH4oMNQh3N75nXWJ3sqdOJ59k1rWpc4U+VtKnjCXviE2Zohn0Nm2KvfFUsvnshsoQzj5PsR5zJg0lV4D6m3E2dlKDDA/YSQqsM5TctzMMNZViYamNALmex3Y44MBFv6FgT+WhXMTIInyqYmo3UjytMiL81zvWq8sLhCfK0kmBemfnLQ07c8Trx7QzSATndFV/PEAYRbISvv5Wdf35chcrqUZZlt8Wjg8283izsxmYFIFn8uWNbfvq13cPSZi/+L6zxlIE1UEWse0ItAAdcO6UcYx4sWEVYmY1M6R4ltP57hRb2jgYJTjP3Xq8seKF97ruJLJQnPLO38ev81Ci/iFQWvhwcEbXusHfm5GOv+SDOTWlg4R8+od/Ylb5Q/6YnjaAFBB+WNMvef91QD7881dDOEBnJVEQTabtZJ+Yfgz4OOvajTwdhjelKzmRGjMXyMr7CdbXpwFXuk83ppsmaDY96hMpwZEasgX7KpTsRxtNTGeL05yWuYp9IVIj6RbRcIxq/APCqEDcEoEMcnbB+eYWvJAflMKYJ0oOLNcEl7Z+LTgXrP0gedMPXHpqwQ1SpEhCW17dYYGJV+ZQHQg576k4gB3GW07F1VrFPMi7s8ct4gdjqHL6NjFeXxpYhrQXvjkoDcYuXT2EYEcPGHxoQi3yFxaDz1DGHMfDeH2gzswpZGox6tQTrzwgceiQqY6eHk8VdCT7BG9m9EC8NUHi1
  template:
    metadata:
      name: netbird-proxy-token
      namespace: netbird
