apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: netbird
  namespace: netbird
spec:
  displayName: Netbird Embedded IdP
  type: CONFIDENTIAL
  clientId: netbird
  clientSecretSecretRef:
    key: clientSecret
    name: netbird-oidc-credentials
    namespace: netbird
  description: Netbird embedded IdP (Dex) OIDC connector
  grantTypes:
    - code
  baseUrl: "https://netbird.homelab.olav.ninja"
  redirectUris:
    - "https://netbird.homelab.olav.ninja/oauth2/callback"
  postLogoutRedirectUris:
    - "https://netbird.homelab.olav.ninja/oauth2/logout/callback"
  groupsClaim: groups
  realm: homelab
