management:
  # https://netbird.io/docs/selfhosted/configuration
  configmap: |-
    {
        "Stuns": [
            {
                "Proto": "udp",
                "URI": "stun:coturn.homelab.olav.ninja:3478",
                "Username": "",
                "Password": null
            }
        ],
        "TURNConfig": {
            "Turns": [
                {
                    "Proto": "udp",
                    "URI": "turn:coturn.homelab.olav.ninja:3478",
                    "Username": "netbird",
                    "Password": "{{ .NETBIRD_TURN_PASSWORD }}"
                }
            ],
            "CredentialsTTL": "12h",
            "Secret": "secret",
            "TimeBasedCredentials": false
        },
        "Signal": {
            "Proto": "https",
            "URI": "netbird.homelab.olav.ninja:443",
            "Username": "",
            "Password": null
        },
        "Relay": {
            "Addresses": ["{{ .NB_EXPOSED_ADDRESS }}"],
            "CredentialsTTL": "24h",
            "Secret": "{{ .NB_AUTH_SECRET }}"
        },
        "Datadir": "/var/lib/netbird",
        "DataStoreEncryptionKey": "{{ .NETBIRD_DATASTORE_ENC_KEY }}",
        "EmbeddedIdP": {
            "Enabled": true,
            "Issuer": "https://netbird.homelab.olav.ninja/oauth2",
            "DashboardRedirectURIs": [
                "https://netbird.homelab.olav.ninja/nb-auth",
                "https://netbird.homelab.olav.ninja/nb-silent-auth"
            ],
            "StaticConnectors": [
                {
                    "type": "oidc",
                    "name": "Keycloak",
                    "id": "keycloak",
                    "config": {
                        "issuer": "https://keycloak.homelab.olav.ninja/realms/homelab",
                        "clientID": "netbird",
                        "clientSecret": "{{ .NETBIRD_IDP_CLIENT_SECRET }}",
                        "redirectURI": "https://netbird.homelab.olav.ninja/oauth2/callback"
                    }
                }
            ]
        }
    }

  podCommand:
    args:
      - --log-level
      - info
      - --log-file
      - console
      - --dns-domain
      - netbird

  image:
    tag: 0.80.0 # renovate: docker=netbirdio/management

  envFromSecret:
    NETBIRD_DATASTORE_ENC_KEY: netbird-management-secret/NETBIRD_DATASTORE_ENC_KEY
    NETBIRD_TURN_PASSWORD: netbird-turn-credentials/password
    NB_AUTH_SECRET: netbird-relay-secret/NB_AUTH_SECRET
    NB_EXPOSED_ADDRESS: netbird-relay-secret/NB_EXPOSED_ADDRESS
    NETBIRD_IDP_CLIENT_SECRET: netbird-oidc-credentials/clientSecret

  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: h2c

  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: longhorn-static
    existingPVName: netbird-management

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /api
            pathType: Prefix
          - path: /management.ManagementService/
            pathType: Prefix
          - path: /oauth2
            pathType: Prefix
    tls:
      - secretName: netbird-tls-certificate
        hosts:
          - netbird.homelab.olav.ninja

signal:
  image:
    tag: 0.80.0 # renovate: docker=netbirdio/signal

  logLevel: info

  service:
    annotations:
      traefik.ingress.kubernetes.io/service.serversscheme: h2c

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /signalexchange.SignalExchange/
            pathType: Prefix
    tls:
      - secretName: netbird-tls-certificate
        hosts:
          - netbird.homelab.olav.ninja

relay:
  replicaCount: 1

  image:
    repository: netbirdio/relay
    pullPolicy: IfNotPresent
    tag: 0.80.0 # renovate: docker=netbirdio/relay

  env:
    NB_LISTEN_ADDRESS: ":80"
    NB_LOG_LEVEL: info

  envFromSecret:
    NB_AUTH_SECRET: netbird-relay-secret/NB_AUTH_SECRET
    NB_EXPOSED_ADDRESS: netbird-relay-secret/NB_EXPOSED_ADDRESS

  containerPort: 80

  service:
    type: ClusterIP
    port: 80
    name: http

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /relay
            pathType: Prefix
    tls:
      - hosts:
          - netbird.homelab.olav.ninja
        secretName: netbird-tls-certificate

dashboard:
  enabled: true

  image:
    tag: v2.94.0 # renovate: docker=netbirdio/dashboard

  podCommand:
    args:
      - sed -i 's/listen \[\:\:\]\:80 default_server\;//g' /etc/nginx/http.d/default.conf && /usr/bin/supervisord -c /etc/supervisord.conf

  env:
    AUTH_AUDIENCE: netbird-dashboard
    AUTH_AUTHORITY: https://netbird.homelab.olav.ninja/oauth2
    AUTH_CLIENT_ID: netbird-dashboard
    AUTH_SUPPORTED_SCOPES: openid profile email groups
    AUTH_REDIRECT_URI: /nb-auth
    AUTH_SILENT_REDIRECT_URI: /nb-silent-auth
    USE_AUTH0: "false"
    NETBIRD_MGMT_API_ENDPOINT: https://netbird.homelab.olav.ninja
    NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.homelab.olav.ninja
    NGINX_SSL_PORT: "443"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
    hosts:
      - host: netbird.homelab.olav.ninja
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: netbird-tls-certificate
        hosts:
          - netbird.homelab.olav.ninja
