---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-oidc-credentials
  namespace: openwebui
spec:
  encryptedData:
    clientId: AgATZxYet2gz1Of6VtDGIDaStL66v1Z4hJKja87uAnc730z78ePf5irRcv//h5rxJkA7Ge0dB8aAdyUSKwySIRwA67yV52bTPLroyYUuqe3bIRFaUWZJKWWf4gSpwHIXDDKMxhzq67k6fuwvVKT/Y74FgkUGRqmyDF0syvXiZ5dtS/V8wqxlWdS0cng03+JQf468N5LUM2CBW4kYwhfqB9EF2txNKABnAcBC5RVKRMq07VmP2BW645CpqlVCDiRQWeh25GsWDbd6YsA/BgG1uNY+OeN/Kd1TpjVdnMJJG5Kgud376Qmgl8fo7RKB51hnRETUL1yBMc5k/BUZH/deuZJTfvr9JqpWwjr2dAw9DPJvX+fTu2LT7kXQHJbYr74908Yd0JrUCO2yOz4e9DpHvCvWCOlYqN8VDc4D4ZKw7PJgNLPdkue8lNXsifCDARebtGScekXLuWnVfojTxmBPz/fUh/12VT1OJxmt0wGtbV3sPW/XT/abjdMI3/PVU4DCeD/4strplrwoPlehk6tQWtBxIIGD8KPHXiPX6WknNtWVlQ+iiIR6hHTLckCyFZ7f4x9msL8JdFquuv4ICdtJ1RJDajHjEm+GVIomsJKgUW1eN8b1pTptNM6YDPewRi87ASN7988s0semlV8YBtBoqs4p4PA3LX4PABEwBGEurJNVsTDW9HU4W786av3nQ3E8vsXMz1i0ZDNm8dY=
    clientSecret: AgAAGMRkzGpDj+45aIwMQ+DoK1FF9Nlxq7GBYgp8+9HWSdRt5rwQqmMv636bQeGqx3PGzrrCkTTUqzlr1otF7ilrwMWV+mPPjoR+Zz1q0LvlzKmhFngcTtSJJtTT5VQyd62EyxOIuVyNItdJS5SYis4mvrRUBfVnlNIVi6deC+k1s8CiF+EJPOGKeQHV8ozG11ryqK5OqzZNiidd+PT47FEfdVbnNz2dQzPKFK84F8ob9kMgbcQrxW2q1OmTCgbtweQLVq5cKmIBeIuxtomg2PMwyeQNPxwkiCSHzbZ9DA42CzqbvmqyOw4U1Ylz9KeG4AhQZN+mNVVp0pzy4yiOeJ3g9bnUFFO3GjExTxS27IXRkWmhZbR33faOASNeBEgDaiQah7dS4XNCkAPj/cs8tfGkBCfs5vFO5Buc8I0VkZiQGecX8u4sQCX258Y0vIK5fWpc2sBUjypW9w34EaztA5QqNSwcIo1KrIuKBVThqTqE0+RPkJNe73fNpGR8e5bOxjF7truTjSNKpx2VXAizvg92+LvUcd3KmL0NfMHlIeUe2sW6EzbAwhjIK6p98pOl1mo1tk1B638KT6tnHvLyr6Ej0/+XJ8rhcp1LBkQYsAol1eEOej2Hik0G1HO1YerEoiK3TIou15HwpQ2vYLFtbuzyCiuyq422UWbYiclptN3R4B7g70mXbOeY4xY1lOVOSTHYtakHSg/3Mzfhg25wM69c0ycXqMtC
  template:
    metadata:
      name: openwebui-oidc-credentials
      namespace: openwebui
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openrouter-api-key
  namespace: openwebui
spec:
  encryptedData:
    apiKey: AgBswTsYNCb7sVbCDb0veUvParrEEEgrhPZp/FlcZfPYEsp5EZguvqdw50DNwqHwDhXUkMYXDuHopL/SIQ90lX1M9wt09gmVhy2nEAsH1MbZmvDu5Og5o73CfpU3vn6qNAr4TZu201Wg7Iambm9izjLi5czewl+bp5l9c4TaksSfBwbtwmpdk/o8ik9P4C10LRO0PjAlKgBixRnAKlXhaGAGaADbqgyCONk6q1S2LYUix3OpxLeNNaFaXqc8vxj013hDK7Kbjebtqa1excWf3V9WzAFA9S0M6WHerVABM89ZbDKDCMFK6sIdsW4DSnVahHsfk08Yoo7Gc+e5TWLD9lV0TA1LpCwPw0lOSLabEEi73p5Np9Kcl3VIsaa4psd93ZY0U0r68ZgupEekZsSPYbxEJ6Ke4T1bXA1ulXtyvkELa7c+AXCgV9bJFevm9GCXsCrtdwPFBBDf7+0sMjwxn76OmhGpjz4JirZ2iruqxNeHnHyZoBH9MQyrjQee2MKOXuLtsrfYQrFI+6XcdJyvsFG/mhoO0hVglbNGU7ccpf+mQzm3KJJmhAw/pTMW+9ZsQfcOf0PHicfDxEnNv5J0rx3I+U0pEnujuSWpoZ5LrCNBJsie7/nj7UjbwWpd6m5YWGoP+2HzKinnlE1+utcnDlYcYhetyogbZq2SM1FG5wzgdhg+GZN16ICy9V+rfs2IMO7q8n++a6YFRvp7/hkr2vdrqBuykA3N7NzJlVsf4CMUetz7Jd6lTUV9TJgH00geFxrS7MMrFGtOD4Zz5xpMSoY1JkKnj3cvzhfY
  template:
    metadata:
      name: openrouter-api-key
      namespace: openwebui
