# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    hajimari.io/enable: 'true'
    hajimari.io/appName: 'OpenWebUI'
    hajimari.io/icon: https://avatars.githubusercontent.com/u/158137808
  host: openwebui.homelab.olav.ninja
  tls: true
  existingSecret: openwebui-tls-certificate

pipelines:
  enabled: false

terminals:
  enabled: true
  networkPolicy:
    enabled: true
    terminalPodSelector:
      app.kubernetes.io/component: null
      app.kubernetes.io/name: open-terminal
      app.kubernetes.io/managed-by: terminals

persistence:
  enabled: true
  provider: local
  existingClaim: open-webui

ollama:
  enabled: false

enableOpenaiApi: true
openaiBaseApiUrls:
  - https://llm-proxy.homelab.olav.ninja/v1
  - https://openrouter.ai/api/v1

extraEnvVars:
  - name: ENABLE_LOGIN_FORM
    value: "False"
  - name: ENABLE_PASSWORD_AUTH
    value: "False"
  - name: ENABLE_PASSWORD_CHANGE_FORM
    value: "False"
  - name: ENABLE_OAUTH_SIGNUP
    value: "True"
  - name: OPENROUTER_API_KEY
    valueFrom:
      secretKeyRef:
        name: openrouter-api-key
        key: apiKey
  - name: OPENAI_API_KEYS
    value: "none;$(OPENROUTER_API_KEY)"
  - name: OPENAI_API_CONFIGS
    value: '{"0":{"enable":true,"connection_type":"openai","provider":"llama.cpp"}, "1":{"enable":true,"model_ids":["openai/gpt-5.6-luna","deepseek/deepseek-v4-flash-0731","z-ai/glm-5.3-flash","z-ai/glm-5.2","nvidia/nemotron-3-ultra-550b-a55b:free","poolside/laguna-s-2.1:free"]}'
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "True"
  - name: OAUTH_AUTO_REDIRECT
    value: "True"
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientId
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientSecret
  - name: OPENID_PROVIDER_URL
    value: https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid-configuration
  - name: OAUTH_PROVIDER_NAME
    value: Keycloak
  - name: OAUTH_SCOPES
    value: openid email profile
