# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: openwebui-sablier@kubernetescrd
    hajimari.io/enable: 'true'
    hajimari.io/icon: https://avatars.githubusercontent.com/u/158137808
  host: openwebui.homelab.olav.ninja
  tls: true
  existingSecret: openwebui-tls-certificate

pipelines:
  enabled: false

terminals:
  enabled: true
  networkPolicy:
    enabled: true

persistence:
  enabled: true
  provider: local
  existingClaim: open-webui

ollama:
  enabled: false

enableOpenaiApi: true
openaiBaseApiUrl: https://llm-proxy.homelab.olav.ninja/v1

extraEnvVars:
  - name: OPENAI_API_CONFIGS
    value: '{"0":{"enable":true,"connection_type":"openai","provider":"llama.cpp"}}'
  - name: ENABLE_OAUTH_SIGNUP
    value: "True"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "True"
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientId
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientSecret
  - name: OPENID_PROVIDER_URL
    value: https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid-configuration
  - name: OAUTH_PROVIDER_NAME
    value: Keycloak
  - name: OAUTH_SCOPES
    value: openid email profile
