# https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    hajimari.io/enable: 'true'
    hajimari.io/appName: 'OpenWebUI'
    hajimari.io/icon: https://avatars.githubusercontent.com/u/158137808
  host: openwebui.homelab.olav.ninja
  tls: true
  existingSecret: openwebui-tls-certificate

pipelines:
  enabled: false

terminals:
  enabled: true
  networkPolicy:
    enabled: true
    terminalPodSelector:
      app.kubernetes.io/component: null
      app.kubernetes.io/name: open-terminal
      app.kubernetes.io/managed-by: terminals

persistence:
  enabled: true
  provider: local
  existingClaim: open-webui

ollama:
  enabled: false

enableOpenaiApi: true
openaiBaseApiUrl: https://llm-proxy.homelab.olav.ninja/v1

extraEnvVars:
  - name: OPENAI_API_CONFIGS
    value: '{"0":{"enable":true,"connection_type":"openai","provider":"llama.cpp"}}'
  - name: ENABLE_LOGIN_FORM
    value: "false"
  - name: ENABLE_PASSWORD_AUTH
    value: "false"
  - name: ENABLE_PASSWORD_CHANGE_FORM
    value: "false"
  - name: ENABLE_OAUTH_SIGNUP
    value: "true"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "true"
  - name: OAUTH_AUTO_REDIRECT
    value: "true"
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientId
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientSecret
  - name: OPENID_PROVIDER_URL
    value: https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid-configuration
  - name: OAUTH_PROVIDER_NAME
    value: Keycloak
  - name: OAUTH_SCOPES
    value: openid email profile
