ollama:
  enabled: false # Deployed separately

ollamaUrls:
  - http://ollama.ollama.svc.cluster.local:11434

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-sablier-ollama-openwebui@kubernetescrd
    hajimari.io/enable: 'true'
    hajimari.io/icon: https://avatars.githubusercontent.com/u/158137808
  host: openwebui.homelab.olav.ninja
  tls: true
  existingSecret: openwebui-tls-certificate

pipelines:
  enabled: false

persistence:
  enabled: true
  existingClaim: open-webui

extraEnvVars:
  - name: ENABLE_OPENAI_API
    value: "False"
  - name: ENABLE_OAUTH_SIGNUP
    value: "True"
  - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
    value: "True"
  - name: OAUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientId
  - name: OAUTH_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: openwebui-oidc-credentials
        key: clientSecret
  - name: OPENID_PROVIDER_URL
    value: https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid-configuration
  - name: OAUTH_PROVIDER_NAME
    value: Keycloak
  - name: OAUTH_SCOPES
    value: openid email profile
