apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pingvinshare-postgresql
  namespace: pingvinshare
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: Europe/Oslo
  bootstrap:
    initdb:
      database: pingvinshare
      owner: pingvinshare
  storage:
    size: 10G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: pingvinshare-postgresql
      accessModes:
        - ReadWriteOnce
