---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pingvinshare-config
data:
  config.yaml: |
    general:
      appName: Pingvin Share
      appUrl: https://pingvin.homelab.olav.ninja
      secureCookies: "true"
      showHomePage: "true"
      sessionDuration: 1 week
    
    share:
      allowRegistration: "true"
      allowUnauthenticatedShares: "true"
      maxExpiration: 180 days
      shareIdLength: "8"
      maxSize: "10000000000"
      zipCompressionLevel: "9"
      chunkSize: "10000000"
      autoOpenShareModal: "false"
    
    cache:
      redis-enabled: "false"
    
    email:
      enableShareEmailRecipients: "false"
    
    smtp:
      enabled: "false"
    
    ldap:
      enabled: "false"
    
    oauth:
      allowRegistration: "true"
      ignoreTotp: "true"
      disablePassword: "true"
      oidc-enabled: "true"
      oidc-discoveryUri: "https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid_configuration"
      oidc-signOut: "true"
      oidc-scope: "openid email profile"
      oidc-usernameClaim: "preferred_username"
      oidc-rolePath: "roles"
      oidc-roleAdminAccess: "admin"
      oidc-clientId: "pingvinshare"
      oidc-clientSecret: "${OIDC_CLIENT_SECRET}"
    
    s3:
      enabled: "false"
    
    legal:
      enabled: "false"
    
    initUser:
      enabled: false
