---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: pingvinshare
spec:
  displayName: Pingvin Share
  type: CONFIDENTIAL
  clientId: pingvinshare
  clientSecretSecretRef:
    key: clientSecret
    name: pingvinshare-oidc-credentials
    namespace: pingvinshare
  description: Pingvin Share Client
  grantTypes:
    - code
  baseUrl: "https://pingvin.homelab.olav.ninja"
  redirectUris:
    - "https://pingvin.homelab.olav.ninja/api/auth/oauth/callback/oidc"
  realm: homelab
