---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
spec:
  volumeName: open-webui
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
