- hosts: all
  roles:
    - role: geerlingguy.hdparm
      vars:
        hdparm_manage_config: true
        hdparm_devices:
          - dev: /dev/sda
            options:
              - "apm = 127"
              - "spindown_time = 120"
