- hosts: all
  become: yes
  tasks:
    - name: Add vfio-pci to /etc/modules
      lineinfile:
        path: /etc/modules
        create: yes
        line: "{{ item }}"
        state: present
      loop:
        - "vfio"
        - "vfio_iommu_type1"
        - "vfio_pci"

    - name: Add vfio-pci options for Vega 56 GPU
      ansible.builtin.lineinfile:
        path: /etc/modprobe.d/vfio.conf
        create: yes
        line: "options vfio-pci ids=1002:687f,1002:aaf8"
        state: present
