- hosts: all
  become: yes
  tasks:
    - name: Install sanoid
      ansible.builtin.package:
        name: sanoid
        state: present

    - name: Create cron job for backing up rpool with syncoid
      ansible.builtin.cron:
        name: "backup rpool to backup disk"
        weekday: "6" # Saturday
        minute: "0"
        hour: "1"
        job: "/usr/sbin/syncoid --no-sync-snap -r rpool backup/rpool"
