- hosts: all
  become: yes
  tasks:
    - name: Create zfs-send user
      ansible.builtin.user:
        name: zfs-send
        groups: users
        create_home: yes

    - name: Add SSH key to zfs-send user's authorized_keys
      ansible.posix.authorized_key:
        user: zfs-send
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD5XLeacrYvhx/GEcrbvsqcadaGWxig/ajTuctpa6NO9z5YUgJbGYk8ZrK1oYOrfMdYNkGnfn9LknW5xmSQsc8E5c3A584+NZzovbuoxKUYAZZkkNt1I9r1vtvuDKy7inDtywWXqbgIPb2nmuMC5WG5xEwNeUbtF4hQ/K5VJrrIgbd8cBvFi698JRdebZScmetOQ6tcR0rUzIuF/99YHsGvB1I1ZMRErKOWPWSRZP2E8sgsw+Q9mSxseTyupa4GrzGbm/onkuF6ZhVcy2ZGRw2qY0qLOZSugrHYoqqp0orhUnfrSrO6S6oAj4QCE8ttycDBYFZlosOFF1puoxay2iEGYgMBKQTuyHkskRHtTWUq4g8iNLIiIkQaTR/DodCaEpAPklhPFBIIDt5cBZthQVZUnZxGxJfGz8H6zYUI/VLrhhfhs62QUnhGSR1bJKG0KSxZgTuqsHnmLLQ5Lhe8MMgE/mvo5vnUU94f7kDMxeLHKdqroWdBYH6dVBpPFtOlM/s= root@truenas"

    - name: Grant required permissions to the 'zfs-send' user
      community.general.zfs_delegate_admin:
        name: backup
        users: zfs-send
        permissions:
          - send
          - hold
