- hosts: all
  become: yes
  tasks:
    - name: Install zfsnap
      ansible.builtin.package:
        name: zfsnap
        state: present

    - name: Create cron job for snapshotting rpool with zfsnap
      ansible.builtin.cron:
        name: "snapshot rpool"
        weekday: "6" # Saturday
        minute: "0"
        hour: "0"
        job: "/usr/sbin/zfSnap -d -a 60d -r rpool"
