apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
- name: external-dns
  releaseName: external-dns
  namespace: external-dns
  repo: https://kubernetes-sigs.github.io/external-dns/
  version: 1.19.0
  includeCRDs: true
  valuesFile: values.yaml
