# https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/values.yaml
controllers:
  bambustudio:
    type: deployment
    labels:
      sablier.enable: "true"
      sablier.group: bambustudio
    containers:
      app:
        image:
          repository: linuxserver/bambustudio
          tag: 02.08.02 # renovate: docker=linuxserver/bambustudio
        env:
          PUID: 1000
          GUID: 1000
          TZ: Europe/Oslo
          DARK_MODE: "true"
          DRINODE: /dev/dri/renderD128
        resources:
          requests:
            memory: 128M
            gpu.intel.com/i915: 1
          limits:
            gpu.intel.com/i915: 1
            memory: 8096M

persistence:
  config:
    existingClaim: bambustudio-config
    globalMounts:
      - path: /config
  data:
    existingClaim: bambustudio-library
    globalMounts:
      - path: /library

service:
  app:
    ports:
      http:
        port: &port 3000

route:
  app:
    enabled: true
    kind: HTTPRoute
    annotations:
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: 'Bambu Studio'
      gethomepage.dev/icon: https://avatars.githubusercontent.com/u/96461528
      gethomepage.dev/description: '3D printing'
      gethomepage.dev/group: Applications
    hostnames:
      - bambustudio.homelab.olav.ninja
    parentRefs:
      - namespace: traefik
        name: internal
