---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingvinshare
spec:
  volumeName: pingvinshare
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn-static