---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pingvinshare-oidc-credentials
  namespace: pingvinshare
spec:
  encryptedData:
    clientId: AgB6AVC0G8DfPEKjYNVcOdHaI/Xx20vQIq+sG5jnfSjiDpHuBOAOk+dazjJ1tmIYIybyygebVOHswKvo9uCHQiIOoYPOW+9AMYUqdZY2NeCfib5x1w7wUVA0rt4O1gFUHvmFbgUcb5GeEzabe6T0pOiLFgYU0LnUztLb+dFVTdmvhU7/pqAWVtjxAfOw62T3KJpH5y7WRosDNyCxUBEFcQttkKWGL5t9tA5Z/e9dxl7cJ4WIWrQ8IciidkwsqKXD81ysGFgVIlzglPxsQjoGYo7Y8+SuTM/m9R4n7mvQYMEtq3RYRLDmIZguGHunXPD3RmBTh719h7IL+bokf2C9eQj2w0oAHeZ1WRMJoZYKP9f2LV0TcsH93wCV5jEJYf/xVwGNIgZyfoQv7kbcc3hrncf7xeUWlHVqwLfZuH9NVoeObLPnkBAp8LnMvwMTc/h86e6gsRVML9oSrJcrtmxhuCEo/Se8O4OOJFKLIbLyy0PzSEVsgO5CZoW1Ven51+EyTI6GEOJp8pw1zwBmjM0o2MkXb2al8is6kBnkD7cqIK8DaOQqPd0Pzuq34IdWIHIx60l9leoeYG6d05Rp5r4KAJmSKuNKjKhmf4VYoYCs3icR65/RQuBBDE4LXZ+BTE9OyEvr7vKdZQteS5HdYCxMINDiBfVbHofcO3zmAFxxMkxhkyJOMo85v7pCy91ESZ/3uL+YEDKa/3Se
    clientSecret: AgAxLGU9KoY7a7pO9lQNdeEF5z/IugZGcfM8C4eqolsW+1PX0ChD4hnucuhbIW3HaDvDEcV28q4Kwa7t3sHuBIF70+L3Ct0vVSnCeBXsY8kOtYtHkSxhokNGRCjwDLBOv61iWP0MyD0R/xt1uoRjua2O7MmhknkGFgfmZlIr/m4Q0zGK/ZH4r9ARNY4wdsh5FTGiaUspFJnLVTKqryUErcJFLZalKBzatfjUvuUMckKXiCpSlCCXAsFZzrniAvZ9OiXJn9gfRnFh9yhT+C5l9IyGlI0a64tMgJlu68F0YcucO8j39qDjprF3sJhkeDFxE6zrTk0rXM9/P5a490CXxdto3JrX7Jvvuc40S8S9vl6h+bl49wmLtQ6pLZZQ5Apz+HdYP4wtLWDpXAnO+ymVpsGjbg0aCb9UobruynmuZFvFjawqVIznvJLUxQLOpo1c5vNJ3DwWFh2cIR6V35kAicDC7cnyoNe1/wcJYTY+FT7lfnVRV/moQq0nO31h37Nf3CQZQCenmHwbCxyclbGLA7OMBuAFTKEtVXKE0UO27QpA9KbdulXOVbIUMBN89Dl/6tOlrgaAEtFunwOf/rrgm9gUOhAnlFKZC4A7eYOGjtpJti2hypUSfHwsItg7qejPR+Y6daF3qFcNwZgwBi1oK+i33i3ahc5xxuQNq4A5jxSCdYWQgkeN7hIZZfcAyBojmTXmYwm08MisNJMbB7/9QsibgEFHYUMH
  template:
    metadata:
      creationTimestamp: null
      name: pingvinshare-oidc-credentials
      namespace: pingvinshare
    type: Opaque
