apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
spec:
  imageName: ghcr.io/corentingiraud/cnpg-pgvector-vectorchord:16-migration
  instances: 1

  postgresql:
    parameters:
      timezone: Europe/Oslo
    shared_preload_libraries:
      - "vchord.so"
      - "vectors.so"

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 5G
    pvcTemplate:
      storageClassName: longhorn-static
      volumeName: immich-postgresql
      accessModes:
        - ReadWriteOnce
