apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-1.1.1@sha256:4a26ca6aad2482289f4a3d3317ccbf1439ce3de140994598375a1f4c4e2e9f8d
  instances: 1

  postgresql:
    parameters:
      timezone: Europe/Oslo
    shared_preload_libraries:
      - "vchord.so"

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgresql-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 5G
    pvcTemplate:
      storageClassName: longhorn-static
      volumeName: immich-postgresql
      accessModes:
        - ReadWriteOnce
