apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hermes-agent-secrets
  namespace: hermes-agent
spec:
  encryptedData:
    apiServerKey: AgCGj90RbThWSO5EutOnUFUh8lxAqLvQCWn2Uu5bs8wP0UiyaQ1tjYQ+wYW7aihFAlBgQVqPC1HtX9iDjbWXOvKzTRo70YvLJPfoBjyiIjNJNNb//Ljuv8ayG42xsraSFbwZFSsDD/+Q/e8TVmS9mxpdH8/29h2eJ0/PEY6mx2EWJP8u1oETSgk28J6PZFmq/42btFAKs7NzW4Rj8A0MtktU/b6FWyX3u+WAhjl3N8uQ3gyiquk/dH0wiUET91oWPqyfOdTs6+q0iXtdUsOP5X4M9AhpQOwu0Xim6seThKpk+qrUId0MTiAFSDDQaepzyHYn8mTkoVE7Y5tILm1Uwo3ILWuuQI/pFSbGuwudP3F0GX8DYol5MO9Kixig9rYl6G3wrQylQoInyaE71TbPsIwUZcrh2ETwdc8pRqyaLqVlmHzn7eqWWzJsdCqS26Jp7Ay+UG+bHolFnOlWoRhcOjEKgOHyBh/MfcovC7Y3QXbOSGTdETuKaAXk1AdG52T3GAz0yvqv7obfWxEoz/oThEZcmvizIlT8kHtx9DTyBhcksO88iCbmwQcQ5jOYT+AbjyzVg+SZ5T2SLes8HCzs4CMtLRhojPcwUhcTdKQoIqIPDB/wl/eJHaHKFgSIh9q7wnCAKx/CJEuTzIeK9h/VIOMHMhR+sa3MxOEkYN6CI7byJlUaTT2XTFBjIN3KwQ9tZnPAmp+8B0G0HFaO1B8zBaQhw31Ils1jT3UK
  template:
    metadata:
      name: hermes-agent-secrets
      namespace: hermes-agent
