---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-backend-management
  namespace: netbird
spec:
  strategy:
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-backend-signal
  namespace: netbird
spec:
  strategy:
    type: Recreate
