apiVersion: v1
kind: Namespace

metadata:
  name: csi-proxmox
  labels:
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
