image:
  tag: 0.5.8-rc10-rocm # renovate: docker=ollama/ollama

ollama:
  gpu:
    enabled: true
    type: 'amd'
    number: 1

  models:
    pull:
      - llama2
      - tinyllama

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      hajimari.io/enable: 'true'
      hajimari.io/icon: https://ollama.com/public/ollama.png
  hosts:
    - host: ollama.homelab.olav.ninja
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ollama-tls-certificate
      hosts:
        - ollama.homelab.olav.ninja
