# https://github.com/trueforge-org/truecharts/blob/master/charts/stable/fileflows/values.yaml
image:
  tag: "26.09" # renovate: docker=docker.io/revenz/fileflows

service:
  main:
    ports:
      main:
        port: 5000
        targetPort: 5000
        # Target the OAuth2 Proxy port (4180) to enforce authentication
        #targetPort: 4180

route:
  main:
    enabled: true
    kind: HTTPRoute
    annotations:
      gethomepage.dev/enabled: 'true'
      gethomepage.dev/name: 'FileFlows'
      gethomepage.dev/icon: https://avatars.githubusercontent.com/u/223186409
      gethomepage.dev/description: 'Media automation'
      gethomepage.dev/group: Applications
    hostnames:
      - fileflows.homelab.olav.ninja
    parentRefs:
      - namespace: traefik
        name: internal

persistence:
  logs:
    enabled: true
    size: 1Gi
  data:
    enabled: true
    existingClaim: fileflows-data
    mountPath: /app/Data
    size: 10Gi
  temp:
    enabled: true
    type: hostPath
    hostPath: /var/mnt/bulk-storage/apps/fileflows/temp
    readOnly: false
  media:
    enabled: true
    type: hostPath
    hostPath: /var/mnt/bulk-storage
    mountPath: /media
    readOnly: false

resources:
  limits:
    gpu.intel.com/i915: "1"
  requests:
    gpu.intel.com/i915: "1"
