apiVersion: v1
kind: Service
metadata:
  name: external-cluster
spec:
  ports:
  - name: ingress-port
    port: 443
    protocol: TCP
    targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-cluster
subsets:
- addresses:
  - ip: 192.168.0.81
  ports:
  - name: ingress-port
    port: 443
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: external-cluster-ingressroute
spec:
  entryPoints:
    - webpublic
  routes:
    - match: HostSNIRegexp(`jiyoung.cloud|{subdomain:[a-z]+}.jiyoung.cloud`)
      services:
        - name: external-cluster
          port: ingress-port
  tls:
    passthrough: true
