---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-setup-key
  namespace: traefik
spec:
  encryptedData:
    setupkey: AgABoc3LquXGAbkQTZyhKvRT+JTSSFemrCPZr+td5H3a/WO3OWLO8peO0K1MMe8LkJ5VjQvarFgAzxD4om7X/9OhnvjwY94sOtr7licFT2pMCQF+HkEcTaNVfWZZA9AUa17FQNM3XsSe2pJaw77fgoWDVguH7Y+inLeFt5vQ/SfnCGrXbCu3aEfjzwT+WgRMq+UNScX9Ry+wY3F4NrToGSR0zwkxHFPcd0jvsCUTFJGwYkM51+JpB7Ju/UTzOIyC3xZQTgzhpFvLwk9XbQqHKYhcP6fVKn5WUEAj93yzSowxfOcvqZTFWtFa+Nu7QgjimqyWmQqvOEzCn7SFj8iSqYEd0ocQp1g0Lv1Avt/2zaVlc7xweHAS68k0iZ5vYBinFCqla1fPmlUQdwydhsnVVnEctwuoaOEt6iztoVkN9u+W1hIn9aoacH1Ag6ieIbSfZBeDDbjV0OxPy8D1BLVQhIsHY8u8IlppYDXrYd6YPvr6Yc/n2+OIgsG8r6hVbdPeSjTfbRAXTPgqpDI3aThLugPHe1oPZW7mmoMhcWOlZkxv/8ciBTx2M0xP0Uz/hiXehyfOGC+XNgNuxm9wXyZ6xAVnCuGNVoTyahSGfNGPVkstWZpYhMtKscZupy6E8j6ObFvKkN2Nasvj0wDYhEAE+daLfovUNpdUhx0uWRg89iNyV2tZmQWBH/yv2QEyMF0qNAUftxVQU22DVHHnNfg/SyvS5BGnYtCJDdOammxEtt9lmSAkSWM=
  template:
    metadata:
      name: netbird-setup-key
      namespace: traefik
