apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak

resources:
  - certificates.yaml
  - cnpg-database.yaml
  - groups.yaml
  - namespace.yaml
  - secrets.yaml
  - realms.yaml
  - users.yaml
  - builtin-objects.yaml

helmCharts:
- name: keycloakx
  releaseName: keycloak
  namespace: keycloak
  repo: oci://ghcr.io/codecentric/helm-charts
  version: 7.0.1
  valuesFile: values.yaml
