---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-password
  namespace: keycloak
spec:
  encryptedData:
    pazzword: AgBgtRvU9pbVKgL7wZQnogcTXA+I8XO3BqAzialWSeeX3YpYCBbhNELkTe4BcugoYfL+keC/0D2VqiECisYL4arvUkOmHXKBVUsl97rzSKcS8zSomy4OMx3lQWI6xBuB4vwLzDN6qcl+LfnoIJlzcycpgQhdWPPcEJ3utzp/dhO9LzocCW2xHREgaySYSkuaTBdq/Tj2HZKuaJ7hVNgbO00zjHZd7qAs0OVFoZpJlZyMYdZU0S1r0gL+XaP3v2ARZ3XQEDmmxufLOPWcxYOeJ712q8wFZn5sCJdns31sFCFYI5mN/d6iBvcEfuWLnCz1ET0DC6HgedLID1jB3sCjYnQdz92V2fkDyj6uzqb7X9CTKwn6JvY8Egd40KVbamsLuoiT2aNpFw23gkK3Ajus3H5S9aL3k8zCSgBrHBKkO2TZDER6Fzw39cLBSnRBWzPS7wy10JIfRNPKV9rmGlHWY6y+H4KWkPiIlUOqDGjlfaLPXyD9o0DcTs3rTPF/lScqPtqSlKJCEDwWqudC8UKLn5YSPfECdOnqNCDyj586h+FZk0IxU4MSG7HbLHi+B3/Aev3qibBeMIYSsUYGn+B61YY0INm+AEV+M2Co98WU46S7+zIHpxSK6LxV+ov6MIdyo1tGC4PnFd1bIZ2ZxjlUnwMfE8tFSyWO+963ECVcPx0rXbvEDnzKvPsW4f25ttk0zzjX2WLxOfs6fcOKnoeGnG+U
  template:
    metadata:
      name: keycloak-admin-password
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-initial-passwords
  namespace: keycloak
spec:
  encryptedData:
    jiyoung: AgBcUBmxePlb1zMfM3AuCjb5l94cq0Y/wo4aKaM8Zf64oGxJfsdV62hYasXdgAhXrzOpOwV+gS1pJxlgGZXBhRecfT8pGJ565BpN6BUW3S3tlBzKKz9KQeywdTWSNwro/H+y/ySGxvmBQcK5MrFitbkaWegyh8XiNZi6zwKshIfYYrS67h19bfjmlKREPbMtO4ML0ABm1aK1PvNIk6ootKpJrap+XcBtnKPJXyF80qrOBcQvrN8z+MXzBcP4hvYB9bnaqGdsR70DLH5H4HfBo6HkWdYYO61ymcz1x/rQ3xFATR9+cZYLEQrgvHGOzGbvLXbbNGmTEQf6oouN8p0y2zIFb7s3UtxfhbSvYbx7ynXuZXGzemB87uSH/+hdLcg2zwxM9BpAJvnyml6n5EkXYINIKiOUPc39Xx59DKy/sdhAxNat9XkUY3T+Hjy1POGrHQ7CYvwVKqF57ffpH7T4ZVmbU3PCdqJg0NSfUO8/K4gILareKM3/a5ljHyBBSnajpJDMc2ZI2OtCGPWyhWLkzB5DuiB7NOEkgKnv8fsoAmNuT85VoHrYUAafIUn06rQ+TB3Zbeyc682UQm4A8AuZbjsnbA5lEBkznhXltceUPkjsM9vC4o9NGsdgw2y0IALRDzCiY9QPoiNYDSihSwmdR2qWR+HmH5tRvd+W6y88wwT1uNSChYq5ZhV1WelDKTdmgqd5d20yw0UJgm67JipXEH0=
    olav: AgA3vrrT4IljgWy68cCPOStbZdOqo8dpAVtXvSYTyhogPOJQgW/tC1LOPEkrrUbEqMbeahYJ4NihjmKROaeVyuY7Ll3cbLtocxbGKT46xsaJmwRqj6D/cEeOUyK2F1pCBdUHsIrElknZoLTX78JqtuxTvcA4vEz0RHHcuTTqZfSeXxNteYrWbUfBaY7ZPW4RX5CU+s5cInJLYAS/N7asj9ZB5v84vy/WHZI/AQmO7IBcn2KV3WC84HAxtFNxXQee9MAQiutyLjXoC1tdTWIxZ/mI64qU4cq3Nq0AARcLmEh+Q+7eGLzC3xDxIJ3s0DzgJ11qpgcd491VG78PcyQXvAHDHUTasQoqMqgvgSsTDO3dPP2lPxaEgRjzCXIwxSLUOmQtqHQ5qEXxTtSnSuvL/JQ3jM6Q1Xcc+kzD+4ail2ROu09/pNJFUZwLMS8y140+vH6FZn3CZFLVrKkSxsL04xWCE+DCblHIg1MCW5bt0QvaCqHm0BhiJwInG113XrqNxIvJMzf596G6Qebl6AyhLOBCeoC6iehN0xc2lO6oAl8S8Q4hbmJsUzOam1s3eNlnqROuqjOqj8BY8GlwfyL1fmVpSUg6GrHwwH9Ie+3ZWy9NvNmSrBiCm9v00CGL/6RBkMkHVmDsiIBWrMyNDEmDOAMMmm0AiSWz9TKiyy63PPpE8Cfo6fu9k5+4mGjd6vR5pRF4xu8lOt5Yycg59hzOb9zS
  template:
    metadata:
      name: keycloak-initial-passwords
      namespace: keycloak
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crossplane-keycloak-credentials
  namespace: keycloak
spec:
  encryptedData:
    credentials: AgBTjhI8iY1NIToAtBAbRe9qVikwtCVKzH52DYazQICVjjHOBOmG+XHQ0XSnopit6le+ayC9ls2pp3zRMXacMyd6a9x5qmFcO9N0hTxPa9F9O2tuwAjUBaWWegM+WgMu2DXa/9nYdKi0Kz1HSDy0gnB9Wtlmd4Xjbr/tYpDRVTRKizCgs1LLNr7/o6G/ZV0zrJH0Hxt85cZNPjSIoODu4v69ea/Xq8ioqSC6GvfThFQdwx1CZi/TS1OAHarpSWl+i3RfPEls46iLNhHi3t8tD1YumSCENqpFtQ3B1jMc5kAE4kGtsvA9RdrGp8oDLIurmWOzL7HeYSJILrB6cVo7L+Y9wnI+ovCeyqbHeGIjBnYUUYTW7kvubbhBzzdhwDDVsUk5/3TYV8eQoccvYWPfmOhzIGEmBH7jOdD7TfCvbx1TMv2cuMjTGoE2A0WBE+hHY/OgtlWN+Mgvld83KvMLW8cNp2Q4ZhY+syo5okgkAUUqUbsw17bGpBnGObsipdB2j/PqqGTHlNcqskK46TVsu8MPV2MwWcZ/UfDbiEyA9GVYFB8aZXtoNwhXsRLNVS874K3HbtiMoNNWYaZ3ddairQl8uomhEm/H/33IiRJwElFgKfQvQOr5ak6yoBC75NoFetz4fZLr0XgWgB2RvIckb3+WxjrCmc5IdrlrL221otu70T1bZcvZN1vaDA9V2AseY7/WZJuGDqHpfeARkdXzDJd99LPW1Ww6eGBru1BQQWi0obilE+dVEueJ9neebkmZX07OTU1dOQRVvHFQb7k0U39s646mseV5g62d5J+2dnxE9bwoYdy9XY2Hu/oCqPW3ezgyENy0rjwhJo3ua36P2BSkDGI694N7EEb2GjuZSZKlDCWaAmfEGhj4Fw9z
  template:
    metadata:
      labels:
        type: provider-credentials
      name: crossplane-keycloak-credentials
      namespace: keycloak
    type: Opaque
