---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: olav
spec:
  forProvider:
    enabled: true
    username: olav
    initialPassword:
      - valueSecretRef:
          key: olav
          name: keycloak-initial-passwords
          namespace: keycloak
    realmIdRef:
      name: homelab
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: jiyoung
spec:
  forProvider:
    enabled: true
    username: jiyoung
    initialPassword:
      - valueSecretRef:
          key: jiyoung
          name: keycloak-initial-passwords
          namespace: keycloak
    realmIdRef:
      name: homelab
