command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"

extraEnv: |
  - name: KEYCLOAK_USER
    value: admin
  - name: KEYCLOAK_PASSWORD_FILE
    value: /secrets/admin-creds/pazzword
  - name: KC_PROXY
    value: edge
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KEYCLOAK_FRONTEND_URL
    value: "https://keycloak.homelab.olav.ninja"
  - name: KC_HOSTNAME_PATH
    value: "/"
  - name: KC_HOSTNAME_URL
    value: "https://keycloak.homelab.olav.ninja"
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://keycloak.homelab.olav.ninja"
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    memory: 3072Mi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, webpublic
  rules:
    - host: keycloak.homelab.olav.ninja
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - keycloak.homelab.olav.ninja
      secretName: keycloak-tls-secret

dbchecker:
  enabled: true

database:
  vendor: postgres
  hostname: keycloak-postgresql-rw
  port: 5432
  database: keycloak
  username: keycloak
  existingSecret: keycloak-postgresql-app

service:
  type: ClusterIP
  httpPort: 8080

http:
  relativePath: /
