apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea

resources:
  - ingress-route.yaml
  - namespace.yaml
  - middleware.yaml
  - oidc-client.yaml
  - pvcs.yaml
  - secrets.yaml

helmCharts:
  - name: gitea
    releaseName: gitea
    namespace: gitea
    repo: https://dl.gitea.io/charts/
    version: 10.6.0
    valuesFile: values.yaml
