apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: ghcr.io/crossplane-contrib/function-extra-resources:v0.0.0-20250728070002-0fc1f1591d98 # renovate: github-releases=crossplane-contrib/function-extra-resources
