apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-extra-resources
spec:
  package: ghcr.io/crossplane-contrib/function-extra-resources:v0.1.0 # renovate: github-releases=crossplane-contrib/function-extra-resources
