apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbird

resources:
  - jobs.yaml
  - netbird-groups.yaml
  - secrets.yaml

helmCharts:
  - name: kubernetes-operator
    releaseName: netbird
    namespace: netbird
    repo: https://netbirdio.github.io/kubernetes-operator
    version: 0.1.13
    includeCRDs: true
    valuesFile: values.yaml

patches:
  - path: patches/fix-nbpolicy-ports.yaml
