apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbird

resources:
  - gateways.yaml
  - network-routers.yaml
  - tcp-routes.yaml
  - secrets.yaml

helmCharts:
  - name: netbird-operator
    releaseName: netbird-operator
    namespace: netbird
    repo: oci://ghcr.io/netbirdio/helm-charts
    version: 0.8.0
    includeCRDs: true
    valuesFile: values.yaml
