apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbird

resources:
  - secrets.yaml
  - https://doc.crds.dev/raw/github.com/netbirdio/kubernetes-operator@helm-v0.1.7 # renovate: github-releases=netbirdio/kubernetes-operator

helmCharts:
  - name: kubernetes-operator
    releaseName: netbird
    namespace: netbird
    repo: https://netbirdio.github.io/kubernetes-operator
    version: 0.1.12
    valuesFile: values.yaml
