apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: netbird
  namespace: netbird
spec:
  dnsZoneRef:
    name: cluster.internal
  workloadOverride:
    replicas: 1
    podTemplate:  # Fix for issue https://github.com/netbirdio/kubernetes-operator/issues/349
      spec:
        containers:
          - name: netbird
            env:
              - name: NB_DISABLE_UPDATE_SETTINGS
                value: 'false'
