---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-operator-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgAztojHciXE2JsHC4ahIQsYgxDAtjD346oimkkLsupPtVzkTOnBlpYMs+UC2JQphAJftoLPjic7sNL5rXp0kbEPAbpoJXOxJ+CpNaPBP+ilc1om0XruO61+LV3xd82Lj4Eg1RbF8ev6t/MYRrQ2S2rpb7Kmn2Ol6L1onVkF+cjz/ZIIyBwrXAUHVgBKLEEpfBkwio6ATXeQqi55crA6oW1RX1E1brH1tDXsBTTYr9gMJjtWvEUV/6dikdmRohgrhmMMFJmOCCbNJh97Qz50fQfvmf5YeSIF93J8K+gsho0VLJV7p0JqTmdlZDxyIcgL6JGPrv6bhuf5SKX7lWqboOQm1QHsyqpUe9QnEvc6E0RHOKOQD1S7tMd5bZ5kYL6j41mPdhi+O/0D4yUOsLlJ+ib3ARuwd4Re+NZqXYagxHYYIJCHcMiVM0Z9p2VU9nAuAw4jJUZaIsUym+SDfXi5PWQXllVqkmmC3D8eCEq/CoUBF6UOiDoEHO8sX6JB0Uf5jo+lrGc9kBOHBo0sRjyAKOQDKUIb1XDyslSQGi0jCwXvvMoMfy8OqQvExySwQ+HnUgTHuWlbhdkYYtzBh888bHgQPqwXslfyvxbcLcdE5oR/DmWZ/mPolB2KhassmyweK778j09rJcqwkZCtH04Y72WDTGz0PFWv5rZvJ90Hf+nQ7yac5yQoVZ+qa24Wm2+tig2/tQ+sHoaAEubE2n0Fw3YbUj1TVlcix9a+l6ktZzpVuyrhOndLu7UV
  template:
    metadata:
      name: netbird-operator-api-key
      namespace: netbird
