# https://github.com/netbirdio/kubernetes-operator/blob/main/charts/netbird-operator/values.yaml
managementURL: https://netbird.homelab.olav.ninja

routingClientImage: netbirdio/netbird:0.76.3-rootless # renovate: docker=netbirdio/netbird

cluster:
  name: cluster

netbirdAPI:
  keyFromSecret:
    name: netbird-operator-api-key
    key: NB_API_KEY

gatewayAPI:
  enabled: true

webhook:
  namespaceSelectors:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
