managementURL: https://netbird.homelab.olav.ninja

netbirdAPI:
  keyFromSecret:
    name: netbird-operator-api-key
    key: NB_API_KEY

ingress:
  enabled: true
  kubernetesAPI:
    enabled: true
    groups:
      - cluster
    policies:
      - cluster
  router:
    enabled: true
    replicas: 1
  policies:
    cluster:
      name: Homelab <-> Cluster Allow All
      description: Allow connections between peers in the homelab group and cluster routing peers
      sourceGroups:
        - homelab
      ports: [] # Ports are added with a patch because of issues with the helm chart. See patches/fix-nbpolicy-ports.yaml
      bidirectional: true

cluster:
  name: cluster

routingClientImage: netbirdio/netbird:0.57.1-rootless # renovate: docker=netbirdio/netbird
