apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

resources:
  - namespace.yaml
  - httproute.yaml

helmCharts:
- name: homepage
  releaseName: homepage
  namespace: homepage
  repo: https://jameswynn.github.io/helm-charts
  version: 2.1.0
  valuesFile: values.yaml
