# https://github.com/jameswynn/helm-charts/blob/main/charts/homepage/values.yaml
enableRbac: true

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homelab.olav.ninja

config:
  kubernetes:
    mode: cluster
    ingress: true   # other apps still use Traefik/Ingress today
    traefik: true
    gateway: true   # << picks up the new HTTPRoute

  bookmarks:
    - Infrastructure:
        - Keycloak:
            - href: https://keycloak.homelab.olav.ninja
        - Longhorn:
            - href: https://longhorn.homelab.olav.ninja
        - Traefik:
            - href: https://traefik.homelab.olav.ninja
    - Networking:
        - OpenWrt:
            - href: http://192.168.0.1
        - Netbird:
            - href: https://netbird.homelab.olav.ninja
    - External:
        - Cloudflare Dashboard:
            - href: https://dash.cloudflare.com
        - Github Repo:
            - href: https://github.com/olav-st/homelab
    - Utilities:
        - Hubble:
            - href: https://hubble.homelab.olav.ninja

  services:
    - Applications:
        - Home Assistant:
            href: https://homeassistant.homelab.olav.ninja
            icon: https://brands.home-assistant.io/homeassistant/icon.png
            description: Home Automation

  settings:
    title: Homelab
    theme: dark
    color: slate

  widgets:
    - greeting:
        text_size: xl
    - search:
        provider: google
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: cluster
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true