apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: Europe/Oslo
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      import:
        type: microservice
        databases:
          - gitea
        source:
          externalCluster: postgres-subchart
  storage:
    size: 10G
    pvcTemplate:
      storageClassName: proxmox-csi
      volumeName: gitea-postgresql-cnpg
      accessModes:
        - ReadWriteOnce
  externalClusters:
    - name: postgres-subchart
      connectionParameters:
        host: gitea-postgresql.gitea.svc.cluster.local
        user: gitea
        dbname: gitea
      password:
        name: gitea-postgresql
        key: password
