---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  volumeName: gitea
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgresql
spec:
  volumeName: gitea-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: proxmox-csi
