---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
spec:
  volumeName: gitea-longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
