realm: coturn.homelab.olav.ninja
replicaCount: 1
extraOptions:
  - --listening-ip=0.0.0.0

certificate:
  enabled: true
  dnsName: coturn.homelab.olav.ninja
  issuerName: letsencrypt

users:
  - name: netbird
    secretKeyRef:
      name: netbird-turn-credentials
      key: password

service:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.0.91
    lbipam.cilium.io/sharing-key: coturn
  type: LoadBalancer
