hajimari:
  title: Homelab
  name: Olav
  lightTheme: gazette
  darkTheme: tron
  namespaceSelector:
    any: true
  globalBookmarks: 
    - group: Utilities
      bookmarks:
      - name: Keycloak
        url: 'https://keycloak.homelab.olav.ninja'
      - name: Netbird
        url: 'https://netbird.homelab.olav.ninja'
    - group: Infrastructure
      bookmarks:
      - name: OpenWrt
        url: 'http://192.168.0.1'
      - name: Proxmox
        url: 'https://192.168.0.190:8006'
    - group: External
      bookmarks:
      - name: Cloudflare Dashboard
        url: 'https://dash.cloudflare.com'
      - name: Github Repo
        url: 'https://github.com/olav-st/homelab'
  customApps:
    - group: Applications
      apps:
        - name: Home Assistant
          url: 'http://homeassistant.homelab.olav.ninja:8123'
          icon: 'https://brands.home-assistant.io/homeassistant/icon.png'

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      hajimari.io/enable: 'false'
    hosts:
      - host: homelab.olav.ninja
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: hajimari-tls-certificate
        hosts:
          - homelab.olav.ninja

persistence:
  data:
    enabled: false