apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openwebui-open-webui
  namespace: openwebui
  labels:
    sablier.enable: "true"
    sablier.group: openwebui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui-open-webui-redis
  namespace: openwebui
  labels:
    sablier.enable: "true"
    sablier.group: openwebui
