apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: homeassistant-backend-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: homeassistant
  validation:
    wellKnownCACertificates: System
    hostname: homeassistant.homelab.olav.ninja
