apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-vm-disk
  annotations:
    cdi.kubevirt.io/allowClaimAdoption: "true"
    cdi.kubevirt.io/storage.populatedFor: "homeassistant-vm-disk"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: homeassistant-vm-disk
  resources:
    requests:
      storage: 32Gi
