apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  instances: 1
  postgresql:
    parameters:
      timezone: Europe/Oslo
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
  storage:
    size: 5G
    pvcTemplate:
      storageClassName: longhorn-static
      volumeName: gitea-postgresql
      accessModes:
        - ReadWriteOnce
