---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-admin-user
  namespace: gitea
spec:
  encryptedData:
    password: AgCGBjrd5MQeC0yx5epmouyLnJ6+5cZkaCiyXlyS4r+KSgvh1bSrtL7yyTI3LXh5ix7scx1j9cpzyRaGHVexM9LNM9XWqC7y7GRNJb3opCoDnSGcZ8PwBuLMTg4sxwM+fIQDq5oci4YyR+Jz8RUnslRCSBVr8qIE6xz1tMlpl16o0ni+vsb9q1AjuO9TTIhnctU/IJ54P4NQI7UYHBV29S7dLiY6R5JwYm992EIqFls6GPEiDGKKzHbphZnznTmlPENmM3fnC2UQzvoUlJ/sP1rbN9HM1gT08GCVnj/3M/W3fUb7dDAE7KAFnFAZSNhhQW2+8+5ipwndQy+CkrV1d3s+TE4rFvsuce87Dm9UTRXMB4brYQb480adZWIJJLxKR5fXy/cWeWOw+mO78FiY3szxgu8pSLUWndCBfRAFoDpuVSoQJJfNyL/9KTJI+IcubLHl+xboF4HpWnfKNRLix2JdYJCs4AmsJNAOcYBGa/fdnOdg6YQ7YhDRuQqlNflgA6UM4lta1mUMFBPdP55qTsdCnpYba0Z1uAWLS4EERVNTgPl0aGLlmmvYqsi8vWpu8JpoNiMFKtk8if0+ldSAQ0Z8ozgSGK7jwz0XWNmbhQLeyf1297qIaenWiNo8GACZbvPHvVOZ9At+xq4jLpMoQA4obMv0WBXpiohaHYq7lLTkFMyN1xFa8ABuguvDR8NjisuuB9tgxTY0zMDAdeQ1qkLKcioao5nxeA4Q
    username: AgA4Du7ge2bBzpz+hHKV3E74rVdFAVoGNs7Qts6Jmr0r3E4dNobiqyroocqsfHK65fOWCfnzBdYN1vKeVml66XG7GalcF21JvnYll9KC0qDRGO5qUW67rtZjG6F6BBV5CJTP4+1+VpNOcQxXdBNnj3WV6M78MhL1oYX1IeB/1tRJjDRgKcRJUc5vArSQAUHoykXq9zNwsib0G+J4EL7MaTfNEZgjpF5pgdb63f2TXiELEufCNzYisF5KyYsEa96NexnCKRowBWQ6TtiQunq4RoYZnxNBNvL03mYhEDpGH5DU/SNWdDRKQf9byaaKaGSgxKKks7a+vUBwYJDoWUd01tQOVN/uaEQwSJ/BazLoQjo244wxhu6yDWuZLfwc2VqlFsG53urT2uPwTv7sNhW5L2PUIWKgOaRhMAlaA9MWgwTfQYvvAOBmlV2GsgwY2IxRGiO0uSNeeAWS5cIhXuc+aZ8vNwj5CZR98WTtZ0E6mmyDmUpXZcakDE8W5enuYR6iejN555jlxK3U4/HvMKe9ywNXzG9LxqzLF40Tm55hH0nJHAFsin9aElfAmpeRY9UcmwIoNWfIHTM2RwFCm//S5GxYLt9uNwYPlfRg/DsREYy2qPNeXth05TbM1IND5ho0Qb6WLB3f0MM39N9YdPsv+nCDPr+Xs8uF/E0tHgowj0LdDgfaPlX+eLOQReiChorjhs3lybBN
  template:
    metadata:
      name: gitea-admin-user
      namespace: gitea
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-oidc-credentials
  namespace: gitea
spec:
  encryptedData:
    key: AgA+nsX7ujf+uzZ2N653HXfGosxZT7zuvHTW/8aZAZ6Ll/wtswLCHwx6G3Sr2u6m8L6AaxhSoUE/RO9NEhQs+xCcTc9J5ODI1lsvd0Qiupw7+EZMn+4EBsT/LjypXfpDvhM9DTbyX7hbJxR04ncJW9q518CHqoT5j4pkm5PLglbmocb85j3QUpBNOaNFAe1SnhwrIoleX1q9BjdeOGP5cj8e4zbaMHTUft3NQyJyi0ghZ2CASEngTQWIVNHbElm04F6xOhnL69YY1Gh+2pO8BJLKRvCE2JA7FgBcRBwvTkGt6q11tbtEaKEoFiMqdEQKdb9AnZa8XErvBljIaZmtIRTsmoU6DZTgBXaFDaEcOKvM/NuSdLUz2j1gKmWZSJ6gMnI9blUxdaV8KHozygbBF0zj2d3eqXpmtI/atmXfbvRduuLLo1vhmaQ++P0vcHZyFlAIQTLJdCGwIt5hdK0SL6uChtYDqhYV+KebuFBmI1r1PKDaurqz+KViSIfK+kt152Mf/LVBq63foszybrDIpNyk2nqlYHJnCAeZ9HtvuZ0Zz5CtAl3KIeWFg1HlynTpNn1GJO/A8wdZRoAOr1JbX5REaoU18HS9n3X6Rrujm5SwydU26AbFT1rrJAVYAjUoufNV3e1HTulcwDjUdAAowvMwciKvpdhh48H2XlFOW3+MZOWBSo8ErVOa8/t9sSowzdqJd3Q+Mw==
    secret: AgB4vQvD4KBUOIkPCBL5+Fgb+jwbt2jvNcucCP0UFZrX3jN40bQxOqcElG1Z/6LZhoq2dh+amkpGIh3R/YKJLNeUsE1TIL9W3ThriO+Ng9AH/K6omywljIldSHsPRARjkAiuUKMlx1mEs7TRw1/YACmXKNw77KL5RO4NLtU7VgxyKcLe3JXIAexbNK6W3X8TkDqu9wx3eNduUet4Jt8jEbaMfINwexE0cH7NRVyQbLDT7i7MxJD1PisQWh6XH1ZGkLkxSxh+wYSHwIHSoMgQT3r4vxJ1rmvDCSEPMEBvB/3tLYYTGWAImffRIdnYHxWD/PDAaSqHqSMGeXtFnduv5SOYK4eSayz1p73IwcTvQc8ePUxgwS8uahN7UYRaoWem1Vs/uw63XBetm5PQX+wh/yvnK1NOdFAFIRn7Oh/iQhoy6kDIdzEndR9WZS0HW8IrMj8oFPTgJh1lRtWyXuhLiYiwsLcmMg6U2sPSJVRcnvxqdG+DqKjWL9WQjaP0EWZe3luole2CMfTkIBcPPJxMd9HJCgCcEdHl9Z5WZ3NPrOGb0DETOnTnn9hJPPlts3QJfqvyygNFqIUkSWE2zrDA4GWF2sMBE8bh8yQYGBD0COwxjvyWvfO0WlZ/63sjTwqeiV229MUGVNquD7BKvShGT71b8UFGfZG8rx5h1WiVnexCJ4Rth/u2eRaxptyD6NO0A43RAMoMJiDatL7ml/LMxfLyhDJvG368rYM=
  template:
    metadata:
      name: gitea-oidc-credentials
      namespace: gitea
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-postgresql
  namespace: gitea
spec:
  encryptedData:
    password: AgCG5I1alY74KUfK2r0gwZxaTrLD2py2Q7vBPPW+4LQg8KA+lTjYUEhN5BZLHzFRUtHW+KQVqqgxRlKOAsRZn55tgzzqxgmNxlipIuX1fGyb5Ds45azqT45nWfJlzf50r0WByMSjsdvVshkNjFjCXlPfwr2r73x+ZWqRv75Ra+6YsPHGWvkzglMQ8G04T+s2crb2PiqtOeSGsflJazLG5VAf8tddChGKsptPwate0UogTctFGHwhjMsTp/J2ivTqOh+VqPSknNuyJQfzYWHTrEHhNR4dNROy1lxFjA2/bbpUoezx4OHEmMB2iKmhVFycLPcxKG0IOykINLO11chia/sStL/3FQSJw0v99YqmgOl4g6HmkCiUSMQyULm2hdAsfbkgt6mGbSTqFkXS+uKClW5WKU0tzowXWQXZ4tCSC4ODZGDRuWbAsipClQLSknd9plh5FEzsrXu5Gujg+ALFDFef6lv6ukd6e9tOlAB68mMklXUVuas3a7JKSeZgYf4+JucmDyn1pDNpyT7KnOzP2GrQ77vTkfgay3QOZ4zh1CMw+5oxrdRbML0JcDvOTBraOKAu+nVwZCWK5nLmS81qj4fWRvqdiklw457cu9m9DZYJIgcp2OGKddyvyH/O8p5JqkmsRowd6LcmUt9F+/9ibnO3z/L9X1+pQkIfDnyBWdoGgIO1MSQzzsoqDdd+MDOxdZZTV9yYkQ==
    postgres-password: AgCfEmOIW7DTsRFmEUsqOAd1+ASfVPxQfZyIcrq1q9LVXX/FWY6dBTmLBpVRPLF1h3acLoUqqIPLGOK0wPgCbr9waEvM9HKsfhFqzTGvPIVid2r2tuga4u0pi0U6JqidcHROpyQCwE2NJrFiY2r3aGo5wstybYzHGDmTIAU8FfCTf38GzqgdneR3Gike9L9IoUmvEXzGu9edcQYinb5+yJ/wWp2+XA9936HmY8vTsjKlv2VWBiu5ZbWO3YRNYOvKesONDgvGh/3I9yagEqajjlpSEIAffDsXRnf16ihqGaxWk6KUD89yOtuiLo5BR9Z2KQmJ2jHB5T/666dZLMUGRgZBxf8G5wR64hSOaAoXI4HZ6xYYsmamGRrVExphzUNrkNu2wHmUwTW3LT8pXG1IyUAd0MZS8ZUlS3RdB6cyczYvhCuln2ER1iLXSPLjKy8HVhvDBwp8deGdvtgXK6USziDbYAaKvosYe5jZynLuEddCFJ55i+Kfk6hPotnnlltlIA5XA9ncK20L6r+tj6Y6CLYR+eShMAi4TS3d3vmmwcWdaqUevh6v+klpCCSJ8JyIP+YTBBl+0fWVNqQDqtAXHzFeU3IRl2MYCZ1pbaLQQgsORabT3tbYbZ1Ab0re56BnIDykw8zwylr2sOOq68laEYqmiXBKEc/9OZZNUFZx2BHE8cx4ewiTkXiCeH917XZRnC60Nlo2zn85v72N
  template:
    metadata:
      name: gitea-postgresql
      namespace: gitea
    type: Opaque
