gitea:
  admin:
    existingSecret: gitea-admin-user
  additionalConfigFromEnvs:
    - name: GITEA__database__DB_TYPE
      value: postgres
    - name: GITEA__database__HOST
      valueFrom:
        secretKeyRef:
          name: gitea-postgresql-app
          key: host
    - name: GITEA__database__NAME
      valueFrom:
        secretKeyRef:
          name: gitea-postgresql-app
          key: dbname
    - name: GITEA__database__USER
      valueFrom:
        secretKeyRef:
          name: gitea-postgresql-app
          key: username
    - name: GITEA__database__PASSWD
      valueFrom:
        secretKeyRef:
          name: gitea-postgresql-app
          key: password
  config:
    service:
      DISABLE_REGISTRATION: true
    server:
      HTTP_PORT: 3000
      OFFLINE_MODE: false
      LFS_START_SERVER: true
    session:
      PROVIDER: memory
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
  oauth:
    - name: keycloak
      provider: openidConnect
      existingSecret: gitea-oidc-credentials
      autoDiscoverUrl: https://keycloak.homelab.olav.ninja/realms/homelab/.well-known/openid-configuration

service:
  http:
    type: ClusterIP
    port: 3000
    clusterIP: None
  ssh:
    type: ClusterIP
    port: 22
    clusterIP: None

gatewayAPI:
  enabled: true
  core:
    httpRoute:
      enabled: true
      tls: true
      annotations:
        gethomepage.dev/enabled: 'true'
        gethomepage.dev/icon: https://upload.wikimedia.org/wikipedia/commons/b/bb/Gitea_Logo.svg
      hostnames:
        - gitea.homelab.olav.ninja
      parentRefs:
        - namespace: traefik
          name: internal
    tcpRoute:
      enabled: true
      parentRefs:
        - namespace: traefik
          name: internal

persistence:
  enabled: true
  mount: true
  create: false
  claimName: gitea

valkey:
  enabled: true
  master:
    count: 1
  primary:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 100m
        ephemeral-storage: 2Gi
        memory: 192Mi
      requests:
        cpu: 50m
        ephemeral-storage: 50Mi
        memory: 128Mi

# Disable unused components
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
redis-cluster:
  enabled: false
valkey-cluster:
  enabled: false

# Use "Recreate" strategy for the deployment
# to make sure that volumes are available when new pod starts
strategy:
  type: Recreate
