---
apiVersion: oidc.homelab.olav.ninja/v1alpha1
kind: XOidcClient
metadata:
  name: zipline
spec:
  displayName: Zipline
  type: CONFIDENTIAL
  clientId: zipline
  clientSecretSecretRef:
    key: clientSecret
    name: zipline-oidc-credentials
  description: Zipline Client
  grantTypes:
    - code
  baseUrl: "https://zipline.homelab.olav.ninja"
  redirectUris:
    - "https://zipline.homelab.olav.ninja/api/auth/oauth/callback"
  realm: homelab
