---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipline
spec:
  volumeName: zipline
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: proxmox-csi
