---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zipline-secret
  namespace: zipline
spec:
  encryptedData:
    CORE_SECRET: AgARTOJtingO6Q1IChVJkwGuRMKMCuKD7kuLP+86ETAfcoi8LvA1L4A0n7s62qft/dgvh0SFVw8N8fiJwY5cpMLzr096dvgz2tayeTb6ijZrwIa+NuaAv/Z+FF5+BNPtRPobtSpEd5okvZIX/dciREw5Dj78e/NWYBasgGr8zI4bcrhkgq5KwqWz9WAoPnX78R7WDSIYeJ3nRQa1nLK54DLZb7pzNSs5AwYOYxC97ydrb2X54Dm+BO+WpAagr729FUXFyAzL6D1ochk5DKgdv0JGRYu0zwiDU2a485GqFQv09FCkhvQpJoUfQ2lM/93rSDRRKB266apoml03qvAITErmpTwUc0C43qU55hniVCWpubWN+AQfxuYt/CnQ++3CZbvSh5JykSq7veuYTKHEau8TPyWmSYbDIkxAO+ILuAOfFQ5YA3RAsYUEQdDLV8u0AhCOZz6Rwqk33HM9uyivZMpiQMpGPSvkLpTnLvlZjZAb2JXYMWLeXZINC/WqbGArYvrTjLA1d85TtrU8zZv+Yp5nhFbX1gpOIAkd+qjQQsz+JC4R8LPGYYOEJ/X3ElIyuUDX+q9j4m44pq63ysq6FJzl7lDFpncHoKDnotQfWoygK0LO5AXXc7DkWhPVeVb6HT1XWZ6i1jac3zTK3XAxkNTrvB9zgplLMdYA18WiUQEy+F3WRwvJASBdyxIbO+gDwYTpdanwUdZHiMTHu+pXNTxt63K9PYzyO75dHKGPd3siFjSoH+3uuB6s0wszAA==
  template:
    metadata:
      creationTimestamp: null
      name: zipline-secret
      namespace: zipline
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: zipline-oidc-credentials
  namespace: zipline
spec:
  encryptedData:
    clientId: AgCK62tOqgA6mc4ZDSE8O8AmOH1QyY5Px/G2oowMIqr/fa2u6J1kNPjm13SbidckuDUqSup3bGjfsGmDDOSlQfLqkRsV8gKcMhcUHP8dxYB60+wEo20YGmTHsxjzF5fZ6wtiEwC+Aoc5PIzUs8++StT7Hgn7Vv2sUbEf0W8j452X2F/emQQTqQoflNKh2Dmep+WB6qJkZmMutrKsotK9eCbrSs9zcmJH5nToaqGaeR8KPMY9p32tsArCSOVk/Rd1T81sLYs/u2WZ5sh8/YfxsnCjrnLm53BITSkRlIJTU7Te7C23LtzGd+RR3wCfsfnTQOhq6smrW06IVipTnQWxK3vEH8ocujOalE9wYu2/D+WEGRZogBuLMj8NtCgd07uHLMXS923x47P4J6bhGBFytVgFahc6ZYNlS7wA9GsS6zqVr9BofOBgGBZsc4smee7vck0y494pz45dV+mmltL6w/TgI412vB6gHnL3P0JWSMSpFNAMfiP8GXj01oM9l/mNcu0w3tv0S4Sr5PLH3b40vnkhJMqt+x8Z5u1mEDqKBQMNc8X4IWN8grgH5fUF6JHiGQf35/bfHDvzveKKoisNc9fVm6cRsBKvdjynDOgfXZeWwuRog1gxv6Ky5C4hRxo50HtTLDV7v/LtNA7W4W3Huhbb2OZDDc7ZlmURhTt+G6GjLTVzaZ2Sud/0yUNbvSYy5GcsnLuzzlUa
    clientSecret: AgAlWn+UowfA13a29JpAjr2CZg0vaBpo8U7pMRPXQhHGsy+XiNPE9kuDG5yV0U4Vxhf7TCWz8+NImlwZieklld8mbbqokt7W6tm+iTrZ+f7Zl7mSpe4naLxlMmb93iExIcY8AKQ8ksgSPOUbhc5YziW5DRgqcQyvbBGaGIuXuoqMb1u1jrHBuTU9a7lKCq/gVvoBE6R19UDE5VJZski/NR1vXlbRgoiKcixPf5v8JRwvVBVgF2Fjxey+bV0wgRtf0g1ammPmKYFwHcDMzGgrcUKMHEKMBUWllcrOu2PAEDrkNwzYFFCvOgKsvYoHFnLitc8KT2xww9MCTaL6zRQIhZwaGJQufVLOH9EOMNUAhbc8seMZ5BbTbmK9dPsjyXoDq9EKp6oJQLVTojrTDc5dHmlZsnnzh4AESwL6mosFF7Q/p4bxKhbucaCJaoE9EwpRVAOz7dVGxqLa3cwmG2JMrVwNVI5+GLc1kLE4wFM12CN1t8aCEOiaaHcz45mZOY76YrHZ1McTXE82O1UoLsRtFOYxufK6HAFYQ4lKx2m1IbS4baxZqE1ZCbwxAJahGXpV/eeh6wYAVtMkfVXqsmNtpBEc3XD6Qj9QGhD0jDO9Kal3Rhgd6pXJywfs0PJDMZh/syDH8iMUpdyB0+ZI+uaOWeSoQQd01fq2S+PYNPH4zep/IE+zp0i+hEAI5Xun7LLdZD3o6lA0zPr5AK3/y/1yMR6E4cRa5tAQ
  template:
    metadata:
      creationTimestamp: null
      name: zipline-oidc-credentials
      namespace: zipline
    type: Opaque
