controllers:
  zipline:
    strategy: Recreate

    containers:
      app:
        image:
          repository: ghcr.io/diced/zipline
          tag: 4.1.2
        env:
          CORE_RETURN_HTTPS: true
          DATABASE_URL:
              valueFrom:
                secretKeyRef:
                  name: zipline-postgresql-app
                  key: uri
          DATASOURCE_TYPE: local
          DATASOURCE_LOCAL_DIRECTORY: /data
          UPLOADER_DEFAULT_FORMAT: random
          UPLOADER_MAX_FILE_SIZE: 10gb
          URLS_ROUTE: /z
        envFrom:
          - secretRef:
              name: zipline-secret
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 5m
            memory: 256Mi
          limits:
            memory: 512Mi

persistence:
  data:
    existingClaim: zipline

service:
  app:
    controller: zipline
    ports:
      http:
        port: 3000

ingress:
  app:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      hajimari.io/enable: 'true'
      hajimari.io/icon: https://zipline.diced.sh/favicons/apple-touch-icon.png
    hosts:
      - host: &hostName zipline.homelab.olav.ninja
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *hostName
        secretName: zipline-tls-certificate
