apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hajimari

resources:
  - namespace.yaml

helmCharts:
- name: hajimari
  releaseName: hajimari
  namespace: hajimari
  repo: https://hajimari.io
  version: 2.0.2
  valuesFile: values.yaml
