apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  template:
    spec:
      volumes:
      - name: config
        configMap:
          name: immich-immich-config
          $patch: delete
        secret:
          secretName: immich-config
