apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud

resources:
  - cnpg-database.yaml
  - namespace.yaml
  - oidc-client.yaml
  - pvcs.yaml
  - secrets.yaml

helmCharts:
- name: nextcloud
  releaseName: nextcloud
  namespace: nextcloud
  repo: https://nextcloud.github.io/helm/
  version: 7.0.2
  valuesFile: values.yaml
