# https://github.com/nextcloud/helm/blob/main/charts/nextcloud/values.yaml
nextcloud:
  host: nextcloud.homelab.olav.ninja
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-user
    usernameKey: username
    passwordKey: password
  configs:
    # allow remote servers with local addresses (for OIDC)
    # add k8s pod namespace to trusted proxies
    # set phone region
    # maintenance window start time to 1am
    mycustom.config.php: |
      <?php
      $CONFIG = array(
        'allow_local_remote_servers' => true,
        'trusted_proxies' => array('10.0.0.0/8'),
        'default_phone_region' => 'NO',
        'maintenance_window_start' => 1,
        );
  phpConfigs:
    uploadLimit.ini: |
      upload_max_filesize = 1G
      post_max_size = 1G
      max_input_time = 5400
      max_execution_time = 5400

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-app
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: dbname

persistence:
  enabled: true
  existingClaim: nextcloud-data

cronjob:
  enabled: true

httpRoute:
  enabled: true
  annotations:
    gethomepage.dev/enabled: 'true'
    gethomepage.dev/icon: https://nextcloud.com/wp-content/uploads/2022/08/nextcloud-logo-icon.svg
  hostnames:
    -  nextcloud.homelab.olav.ninja
  parentRefs:
    - namespace: traefik
      name: internal

phpClientHttpsFix:
  enabled: true
  protocol: https

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: nextcloud-redis-credentials
    existingSecretPasswordKey: password
  # Since Redis is used for caching only, you might want to use a storageClass with different reclaim policy and backup settings
  global:
    storageClass: ""
  master:
    persistence:
      enabled: false
  replica:
    persistence:
      enabled: false
