---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  volumeName: nextcloud-data-longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 310Gi
  storageClassName: longhorn-static
