---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-admin-user
  namespace: nextcloud
spec:
  encryptedData:
    password: AgA133ceVXtfCLHa+fpkKReprcm1tpKZkbpTwYf4tFydhIIO2QLXRD2CioaSDYsk0aNlQUzXZyQJyMfplLs6G7Q0t/2d8cYVgVmEBcdiXgB3CF80gY4/2newgaCQp1MbCYoc28q4scE1vZvqgRfSGWiO12sxPklMWtrAxgIoNz8myEhKEuy42GfneXDUjfN+LvHFSJugDCVBLE4rc5MkNdB40UO6R54zxL40FQf7azZEMcLDIaUfM+ki4445V00rEMA8J9k9DEdPIXwRKva+osIcbKDuWv3L43fEyP0cfj1g5lgNcm+oX/Kmo+Lp48+jvdYOMQCnWW2A19pBIHlym33bPR/ViMkl/o+ztKiH6UxxNy2FyUZkIxKjL+1h/XctiqiNjJg7zCWEn2Mtue0zN0CMSe37ApzE5DzngsHpLAkvJ0DxHq3PPd3l3TevgeVj0hc2gR0sT08TuT9TRKK/EqCcPHpmeKtnzzruV7X+Vl0nreAXS1T/x2COW4FP8RE4RkXSDxf8OPhDy+MSFX5ortwbGM29yOt/9YU1Sq9uDiCj3OeXkFq0wEHCMsaSVJB255cMTR/a8FNrQFIeHT/UkRVQuSCVKAejpeN3EQnMr6ni9BQWu0BVLTwGa3XXQ94ucnmQtye3TwhIz30Hb/4mLloU5jMYUap3NwBp9cMwOxrKyH2HU0cDARAwgsgJhRA6a+OAGPz4eBwxZpuRza5CPRXNefF3cg==
    username: AgApHO0tUVeG++vsB3O4rLN+RrgTFG4uYNvk3lI8+KMV+n3faNak6j+RwhNtwqwcDO+loVQCfvi+mpW9txEqCfTRQ/xbI7oAHGP2fg5YJw4fHFDdKyH5tAeYE27nF21cAjABFymTqkqyD00A7qlorjljc6ld+KUwS67XL0LFsssuNfZQ9bxDjl/Yk2a+4ykNXNYQnMO7hqvxcrIhq9Dbbr8rOFNYTM6ByhBwaU7R5/QgUJ/52Eyb3Og0C97SSesNQUH2UsjHFVEqdMD7dGmdiAdvlA/5wd1V8yFlaUfPkOkWnCpnkpz4frSIMKJwQcIcDF5/YIfMtb/i4AOcUAv9qW4brlS4iCB37juPfItZkUtXm/iHItEAE3E2lkl9f+t1St1f9KuLh3aNOSgfiwTSU26Iw/850ZUjQKhkSXDw4uqiZ7XJC89dT1aavQfPLugj/5U7vuGRkkC+O04x3N6lLbDOqNC7O8H+sIwqd2AnOvVFvGf9ucnyY5ziNuDgNUL8bJQPd06zGh4u15tbOaat4LJ0DbNQACp4Fln9ivipgLvDb/8+WYSmkX2gL2TPMjzoq/FLtB3jgbhGcCDb0gqDkE/UT19JVHjCoBZAHi4Zds4cSknKiqbO8X5mcK4j4dQNutsA5cAbWasjtC18tCySevkmu/6k3oZutg4OYaoiWA0lHwu8AtFlQJGVMg2m4hEp2vaZ0SRsEQ==
  template:
    metadata:
      name: nextcloud-admin-user
      namespace: nextcloud
