nextcloud:
  host: nextcloud.homelab.olav.ninja
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-user
    usernameKey: username
    passwordKey: password
  configs:
    # allow remote servers with local addresses (for OIDC)
    # add k8s pod namespace to trusted proxies
    # set phone region
    # maintenance window start time to 1am
    mycustom.config.php: |
      <?php
      $CONFIG = array(
        'allow_local_remote_servers' => true,
        'trusted_proxies' => array('10.0.0.0/8'),
        'default_phone_region' => 'NO',
        'maintenance_window_start' => 1,
        );
  phpConfigs:
    uploadLimit.ini: |
      upload_max_filesize = 1G
      post_max_size = 1G
      max_input_time = 5400
      max_execution_time = 5400

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-app
    usernameKey: username
    passwordKey: password
    hostKey: host
    databaseKey: dbname

persistence:
  enabled: true
  existingClaim: nextcloud-data

cronjob:
  enabled: true

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    hajimari.io/enable: 'true'
    hajimari.io/icon: https://nextcloud.com/wp-content/uploads/2022/08/nextcloud-logo-icon.svg
  tls:
    - secretName: nextcloud-tls-certificate
      hosts:
        - nextcloud.homelab.olav.ninja

phpClientHttpsFix:
  enabled: true
  protocol: https
