---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-operator-api-key
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgA8zYtFW8T/j49vCrnRB0UVEDDSOTl8AWwEgXrdjslwFAMC72td1DIH6/FZgTwo5L7itaLXXDrfYnyVnIMYGs/AaFC4CZ3l4xSObDrSN/z2gYshDuuWinRalnz5VR5VLhb3P/NcHJmy8Kg8XbuVPTqifA55GCAA7udhOPFW4zR7183M3YpaPzuiuNxqyua9ddwb6TrcGU3pk55UoJi16OPEn60ltqDJ22Ib/7/uzXlvDGDIHjCMH8CpBd8QCmLxlCpi2uWcvAKirF1dCDsw4mRF7Nf8UhGl9XPbOHGxI9ptDrE7ZZ1nNm/hrkOHAeqQUOFrw4iIiC6ZNiItFVvnS3VMyrIj/bhxSuIggqlcNex7By/SRqCuzUGh2E2qaHjCgJVm2OUWlhxZJ+HsoVONWyuZR8qT4dE+keurh6TC6hYOgEcsc94GpNbA9+VdSvY7MS8EXfu5bsNQMH0XpnsFK9EErj6R1tdnnrGiAq7lav+mRPhewe50c6HU5GOMeRlIuJpKAZADYyk27HqkdKaT7Xdosb3kxkRCBwWfCoyawHl9plIYnm6OyZPzpBna9QEd/VXttiYi++XSRbteAVurTeXKGzxvNT3eLHtN/Yr6934jjlZwHT2MtNR4bZGkozmkfr73tAtAZHiGCLGHPNjo7M0vrcjkdkkv4KR7UteG3wbWoo/floJM/Ma7P+k2aSrqUACvx1bdME3qGSDF4ft+leBo2hkcXV65SXN1airHtCKJ+JgRFU1AtE5t
  template:
    metadata:
      name: netbird-operator-api-key
      namespace: netbird
