name: Kubernetes Manifests

on:
  push:
    branches: 
      - '**'
    paths:
      - '**.yaml'

permissions:
  contents: write
  packages: write

jobs:
  render-manifests:
    name: Render
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'GitHub Actions'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Render manifests
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/olav-st/homelab-devcontainer
          cacheFrom: ghcr.io/olav-st/homelab-devcontainer
          runCmd: make render-manifests

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update rendered manifests" || echo "No changes to commit"
          git push origin HEAD

  test-manifests:
    name:  Test
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name == 'GitHub Actions'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test rendered manifests (dry-run)
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/olav-st/homelab-devcontainer
          cacheFrom: ghcr.io/olav-st/homelab-devcontainer
          runCmd: |
            make start-dev-cluster
            make test